// This file may be redistributed and modified only under the terms of
// the GNU Lesser General Public License (See COPYING for details).
// Copyright (C) 2003 Simon Goodall

#ifndef GL_ATI_vertex_streams_H
#define GL_ATI_vertex_streams_H 1

#include <GL/gl.h>
#include  <sage/sage.h>

#ifndef GL_ATI_vertex_streams
#define GL_ATI_vertex_streams 1

typedef void (*PFNGLVERTEXSTREAM1SATIPROC)(GLenum stream, GLshort);
typedef void (*PFNGLVERTEXSTREAM1IATIPROC)(GLenum stream, GLint);
typedef void (*PFNGLVERTEXSTREAM1FATIPROC)(GLenum stream, GLfloat);
typedef void (*PFNGLVERTEXSTREAM1DATIPROC)(GLenum stream, GLdouble);
typedef void (*PFNGLVERTEXSTREAM2SATIPROC)(GLenum stream, GLshort, GLshort);
typedef void (*PFNGLVERTEXSTREAM2IATIPROC)(GLenum stream, GLint, GLint);
typedef void (*PFNGLVERTEXSTREAM2FATIPROC)(GLenum stream, GLfloat, GLfloat);
typedef void (*PFNGLVERTEXSTREAM2DATIPROC)(GLenum stream, GLdouble, GLdouble);
typedef void (*PFNGLVERTEXSTREAM3SATIPROC)(GLenum stream, GLshort, GLshort, GLshort);
typedef void (*PFNGLVERTEXSTREAM3IATIPROC)(GLenum stream, GLint, GLint, GLint);
typedef void (*PFNGLVERTEXSTREAM3FATIPROC)(GLenum stream, GLfloat, GLfloat, GLfloat);
typedef void (*PFNGLVERTEXSTREAM3DATIPROC)(GLenum stream, GLdouble, GLdouble, GLdouble);
typedef void (*PFNGLVERTEXSTREAM4SATIPROC)(GLenum stream, GLshort, GLshort, GLshort, GLshort);
typedef void (*PFNGLVERTEXSTREAM4IATIPROC)(GLenum stream, GLint, GLint, GLint, GLint);
typedef void (*PFNGLVERTEXSTREAM4FATIPROC)(GLenum stream, GLfloat, GLfloat, GLfloat, GLfloat);
typedef void (*PFNGLVERTEXSTREAM4DATIPROC)(GLenum stream, GLdouble, GLdouble, GLdouble, GLdouble);
typedef void (*PFNGLVERTEXSTREAM1SVATIPROC)(GLenum stream, GLshort *);
typedef void (*PFNGLVERTEXSTREAM1IVATIPROC)(GLenum stream, GLint *);
typedef void (*PFNGLVERTEXSTREAM1FVATIPROC)(GLenum stream, GLfloat *);
typedef void (*PFNGLVERTEXSTREAM1DVATIPROC)(GLenum stream, GLdouble *);
typedef void (*PFNGLVERTEXSTREAM2SVATIPROC)(GLenum stream, GLshort *);
typedef void (*PFNGLVERTEXSTREAM2IVATIPROC)(GLenum stream, GLint *);
typedef void (*PFNGLVERTEXSTREAM2FVATIPROC)(GLenum stream, GLfloat *);
typedef void (*PFNGLVERTEXSTREAM2DVATIPROC)(GLenum stream, GLdouble *);
typedef void (*PFNGLVERTEXSTREAM3SVATIPROC)(GLenum stream, GLshort *);
typedef void (*PFNGLVERTEXSTREAM3IVATIPROC)(GLenum stream, GLint *);
typedef void (*PFNGLVERTEXSTREAM3FVATIPROC)(GLenum stream, GLfloat *);
typedef void (*PFNGLVERTEXSTREAM3DVATIPROC)(GLenum stream, GLdouble *);
typedef void (*PFNGLVERTEXSTREAM4SVATIPROC)(GLenum stream, GLshort *);
typedef void (*PFNGLVERTEXSTREAM4IVATIPROC)(GLenum stream, GLint *);
typedef void (*PFNGLVERTEXSTREAM4FVATIPROC)(GLenum stream, GLfloat *);
typedef void (*PFNGLVERTEXSTREAM4DVATIPROC)(GLenum stream, GLdouble *);
typedef void (*PFNGLNORMALSTREAM3BATIPROC)(GLenum stream, GLbyte coords);
typedef void (*PFNGLNORMALSTREAM3SATIPROC)(GLenum stream, GLshort coords);
typedef void (*PFNGLNORMALSTREAM3IATIPROC)(GLenum stream, GLint coords);
typedef void (*PFNGLNORMALSTREAM3FATIPROC)(GLenum stream, GLfloat coords);
typedef void (*PFNGLNORMALSTREAM3DATIPROC)(GLenum stream, GLdouble coords);
typedef void (*PFNGLNORMALSTREAM3BVATIPROC)(GLenum stream, GLbyte *coords);
typedef void (*PFNGLNORMALSTREAM3SVATIPROC)(GLenum stream, GLshort *coords);
typedef void (*PFNGLNORMALSTREAM3IVATIPROC)(GLenum stream, GLint *coords);
typedef void (*PFNGLNORMALSTREAM3FVATIPROC)(GLenum stream, GLfloat *coords);
typedef void (*PFNGLNORMALSTREAM3DVATIPROC)(GLenum stream, GLdouble *coords);
typedef void (*PFNGLCLIENTACTIVEVERTEXSTREAMATIPROC)(GLenum stream);
typedef void (*PFNGLVERTEXBLENDENVIATIPROC)(GLenum pname, GLint param);
typedef void (*PFNGLVERTEXBLENDENVFATIPROC)(GLenum pname, GLfloat param);

#define GL_MAX_VERTEX_STREAMS_ATI           0x876B
#define GL_VERTEX_STREAM0_ATI              0x876C
#define GL_VERTEX_STREAM1_ATI              0x876D
#define GL_VERTEX_STREAM2_ATI              0x876E
#define GL_VERTEX_STREAM3_ATI              0x876F
#define GL_VERTEX_STREAM4_ATI              0x8770
#define GL_VERTEX_STREAM5_ATI              0x8771
#define GL_VERTEX_STREAM6_ATI              0x8772
#define GL_VERTEX_STREAM7_ATI              0x8773
#define GL_VERTEX_SOURCE_ATI               0x8774

#endif

SAGEAPI PFNGLVERTEXSTREAM1SATIPROC glVertexStream1sATI;
SAGEAPI PFNGLVERTEXSTREAM1IATIPROC glVertexStream1iATI;
SAGEAPI PFNGLVERTEXSTREAM1FATIPROC glVertexStream1fATI;
SAGEAPI PFNGLVERTEXSTREAM1DATIPROC glVertexStream1dATI;
SAGEAPI PFNGLVERTEXSTREAM2SATIPROC glVertexStream2sATI;
SAGEAPI PFNGLVERTEXSTREAM2IATIPROC glVertexStream2iATI;
SAGEAPI PFNGLVERTEXSTREAM2FATIPROC glVertexStream2fATI;
SAGEAPI PFNGLVERTEXSTREAM2DATIPROC glVertexStream2dATI;
SAGEAPI PFNGLVERTEXSTREAM3SATIPROC glVertexStream3sATI;
SAGEAPI PFNGLVERTEXSTREAM3IATIPROC glVertexStream3iATI;
SAGEAPI PFNGLVERTEXSTREAM3FATIPROC glVertexStream3fATI;
SAGEAPI PFNGLVERTEXSTREAM3DATIPROC glVertexStream3dATI;
SAGEAPI PFNGLVERTEXSTREAM4SATIPROC glVertexStream4sATI;
SAGEAPI PFNGLVERTEXSTREAM4IATIPROC glVertexStream4iATI;
SAGEAPI PFNGLVERTEXSTREAM4FATIPROC glVertexStream4fATI;
SAGEAPI PFNGLVERTEXSTREAM4DATIPROC glVertexStream4dATI;
SAGEAPI PFNGLVERTEXSTREAM1SVATIPROC glVertexStream1svATI;
SAGEAPI PFNGLVERTEXSTREAM1IVATIPROC glVertexStream1ivATI;
SAGEAPI PFNGLVERTEXSTREAM1FVATIPROC glVertexStream1fvATI;
SAGEAPI PFNGLVERTEXSTREAM1DVATIPROC glVertexStream1dvATI;
SAGEAPI PFNGLVERTEXSTREAM2SVATIPROC glVertexStream2svATI;
SAGEAPI PFNGLVERTEXSTREAM2IVATIPROC glVertexStream2ivATI;
SAGEAPI PFNGLVERTEXSTREAM2FVATIPROC glVertexStream2fvATI;
SAGEAPI PFNGLVERTEXSTREAM2DVATIPROC glVertexStream2dvATI;
SAGEAPI PFNGLVERTEXSTREAM3SVATIPROC glVertexStream3svATI;
SAGEAPI PFNGLVERTEXSTREAM3IVATIPROC glVertexStream3ivATI;
SAGEAPI PFNGLVERTEXSTREAM3FVATIPROC glVertexStream3fvATI;
SAGEAPI PFNGLVERTEXSTREAM3DVATIPROC glVertexStream3dvATI;
SAGEAPI PFNGLVERTEXSTREAM4SVATIPROC glVertexStream4svATI;
SAGEAPI PFNGLVERTEXSTREAM4IVATIPROC glVertexStream4ivATI;
SAGEAPI PFNGLVERTEXSTREAM4FVATIPROC glVertexStream4fvATI;
SAGEAPI PFNGLVERTEXSTREAM4DVATIPROC glVertexStream4dvATI;
SAGEAPI PFNGLNORMALSTREAM3BATIPROC glNormalStream3bATI;
SAGEAPI PFNGLNORMALSTREAM3SATIPROC glNormalStream3sATI;
SAGEAPI PFNGLNORMALSTREAM3IATIPROC glNormalStream3iATI;
SAGEAPI PFNGLNORMALSTREAM3FATIPROC glNormalStream3fATI;
SAGEAPI PFNGLNORMALSTREAM3DATIPROC glNormalStream3dATI;
SAGEAPI PFNGLNORMALSTREAM3BVATIPROC glNormalStream3bvATI;
SAGEAPI PFNGLNORMALSTREAM3SVATIPROC glNormalStream3svATI;
SAGEAPI PFNGLNORMALSTREAM3IVATIPROC glNormalStream3ivATI;
SAGEAPI PFNGLNORMALSTREAM3FVATIPROC glNormalStream3fvATI;
SAGEAPI PFNGLNORMALSTREAM3DVATIPROC glNormalStream3dvATI;
SAGEAPI PFNGLCLIENTACTIVEVERTEXSTREAMATIPROC glClientActiveVertexStreamATI;
SAGEAPI PFNGLVERTEXBLENDENVIATIPROC glVertexBlendEnviATI;
SAGEAPI PFNGLVERTEXBLENDENVFATIPROC glVertexBlendEnvfATI;

SAGEAPI int GL_ATI_vertex_streams_initialised;
SAGEAPI int initialise_GL_ATI_vertex_streams();

#endif
