// This file may be redistributed and modified only under the terms of
// the GNU Lesser General Public License (See COPYING for details).
// Copyright (C) 2003 Simon Goodall

#include <sage/sage.h>
#include "SDL.h"
#include <sage/utility.h>

#ifdef SAGE_GL_VERSION_1_2
PFNGLBLENDCOLORPROC glBlendColor = 0;
PFNGLBLENDEQUATIONPROC glBlendEquation = 0;
PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements = 0;
PFNGLCOLORTABLEPROC glColorTable = 0;
PFNGLCOLORTABLEPARAMETERFVPROC glColorTableParameterfv = 0;
PFNGLCOLORTABLEPARAMETERIVPROC glColorTableParameteriv = 0;
PFNGLCOPYCOLORTABLEPROC glCopyColorTable = 0;
PFNGLGETCOLORTABLEPROC glGetColorTable = 0;
PFNGLGETCOLORTABLEPARAMETERFVPROC glGetColorTableParameterfv = 0;
PFNGLGETCOLORTABLEPARAMETERIVPROC glGetColorTableParameteriv = 0;
PFNGLCOLORSUBTABLEPROC glColorSubTable = 0;
PFNGLCOPYCOLORSUBTABLEPROC glCopyColorSubTable = 0;
PFNGLCONVOLUTIONFILTER1DPROC glConvolutionFilter1D = 0;
PFNGLCONVOLUTIONFILTER2DPROC glConvolutionFilter2D = 0;
PFNGLCONVOLUTIONPARAMETERFPROC glConvolutionParameterf = 0;
PFNGLCONVOLUTIONPARAMETERFVPROC glConvolutionParameterfv = 0;
PFNGLCONVOLUTIONPARAMETERIPROC glConvolutionParameteri = 0;
PFNGLCONVOLUTIONPARAMETERIVPROC glConvolutionParameteriv = 0;
PFNGLCOPYCONVOLUTIONFILTER1DPROC glCopyConvolutionFilter1D = 0;
PFNGLCOPYCONVOLUTIONFILTER2DPROC glCopyConvolutionFilter2D = 0;
PFNGLGETCONVOLUTIONFILTERPROC glGetConvolutionFilter = 0;
PFNGLGETCONVOLUTIONPARAMETERFVPROC glGetConvolutionParameterfv = 0;
PFNGLGETCONVOLUTIONPARAMETERIVPROC glGetConvolutionParameteriv = 0;
PFNGLGETSEPARABLEFILTERPROC glGetSeparableFilter = 0;
PFNGLSEPARABLEFILTER2DPROC glSeparableFilter2D = 0;
PFNGLGETHISTOGRAMPROC glGetHistogram = 0;
PFNGLGETHISTOGRAMPARAMETERFVPROC glGetHistogramParameterfv = 0;
PFNGLGETHISTOGRAMPARAMETERIVPROC glGetHistogramParameteriv = 0;
PFNGLGETMINMAXPROC glGetMinmax = 0;
PFNGLGETMINMAXPARAMETERFVPROC glGetMinmaxParameterfv = 0;
PFNGLGETMINMAXPARAMETERIVPROC glGetMinmaxParameteriv = 0;
PFNGLHISTOGRAMPROC glHistogram = 0;
PFNGLMINMAXPROC glMinmax = 0;
PFNGLRESETHISTOGRAMPROC glResetHistogram = 0;
PFNGLRESETMINMAXPROC glResetMinmax = 0;
PFNGLTEXIMAGE3DPROC glTexImage3D = 0;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D = 0;
PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D = 0;
#endif
#ifdef SAGE_GL_ARB_multitexture
PFNGLACTIVETEXTUREARBPROC glActiveTextureARB = 0;
PFNGLCLIENTACTIVETEXTUREARBPROC glClientActiveTextureARB = 0;
PFNGLMULTITEXCOORD1DARBPROC glMultiTexCoord1dARB = 0;
PFNGLMULTITEXCOORD1DVARBPROC glMultiTexCoord1dvARB = 0;
PFNGLMULTITEXCOORD1FARBPROC glMultiTexCoord1fARB = 0;
PFNGLMULTITEXCOORD1FVARBPROC glMultiTexCoord1fvARB = 0;
PFNGLMULTITEXCOORD1IARBPROC glMultiTexCoord1iARB = 0;
PFNGLMULTITEXCOORD1IVARBPROC glMultiTexCoord1ivARB = 0;
PFNGLMULTITEXCOORD1SARBPROC glMultiTexCoord1sARB = 0;
PFNGLMULTITEXCOORD1SVARBPROC glMultiTexCoord1svARB = 0;
PFNGLMULTITEXCOORD2DARBPROC glMultiTexCoord2dARB = 0;
PFNGLMULTITEXCOORD2DVARBPROC glMultiTexCoord2dvARB = 0;
PFNGLMULTITEXCOORD2FARBPROC glMultiTexCoord2fARB = 0;
PFNGLMULTITEXCOORD2FVARBPROC glMultiTexCoord2fvARB = 0;
PFNGLMULTITEXCOORD2IARBPROC glMultiTexCoord2iARB = 0;
PFNGLMULTITEXCOORD2IVARBPROC glMultiTexCoord2ivARB = 0;
PFNGLMULTITEXCOORD2SARBPROC glMultiTexCoord2sARB = 0;
PFNGLMULTITEXCOORD2SVARBPROC glMultiTexCoord2svARB = 0;
PFNGLMULTITEXCOORD3DARBPROC glMultiTexCoord3dARB = 0;
PFNGLMULTITEXCOORD3DVARBPROC glMultiTexCoord3dvARB = 0;
PFNGLMULTITEXCOORD3FARBPROC glMultiTexCoord3fARB = 0;
PFNGLMULTITEXCOORD3FVARBPROC glMultiTexCoord3fvARB = 0;
PFNGLMULTITEXCOORD3IARBPROC glMultiTexCoord3iARB = 0;
PFNGLMULTITEXCOORD3IVARBPROC glMultiTexCoord3ivARB = 0;
PFNGLMULTITEXCOORD3SARBPROC glMultiTexCoord3sARB = 0;
PFNGLMULTITEXCOORD3SVARBPROC glMultiTexCoord3svARB = 0;
PFNGLMULTITEXCOORD4DARBPROC glMultiTexCoord4dARB = 0;
PFNGLMULTITEXCOORD4DVARBPROC glMultiTexCoord4dvARB = 0;
PFNGLMULTITEXCOORD4FARBPROC glMultiTexCoord4fARB = 0;
PFNGLMULTITEXCOORD4FVARBPROC glMultiTexCoord4fvARB = 0;
PFNGLMULTITEXCOORD4IARBPROC glMultiTexCoord4iARB = 0;
PFNGLMULTITEXCOORD4IVARBPROC glMultiTexCoord4ivARB = 0;
PFNGLMULTITEXCOORD4SARBPROC glMultiTexCoord4sARB = 0;
PFNGLMULTITEXCOORD4SVARBPROC glMultiTexCoord4svARB = 0;
#endif
#ifdef SAGE_GL_ARB_transpose_matrix
PFNGLLOADTRANSPOSEMATRIXFARBPROC glLoadTransposeMatrixfARB = 0;
PFNGLLOADTRANSPOSEMATRIXDARBPROC glLoadTransposeMatrixdARB = 0;
PFNGLMULTTRANSPOSEMATRIXFARBPROC glMultTransposeMatrixfARB = 0;
PFNGLMULTTRANSPOSEMATRIXDARBPROC glMultTransposeMatrixdARB = 0;
#endif
#ifdef SAGE_GL_ARB_multisample
PFNGLSAMPLECOVERAGEARBPROC glSampleCoverageARB = 0;
PFNGLSAMPLEPASSARBPROC glSamplePassARB = 0;
#endif
#ifdef SAGE_GL_ARB_texture_env_add
#endif
#ifdef SAGE_GL_ARB_texture_cube_map
#endif
#ifdef SAGE_GL_ARB_texture_compression
PFNGLCOMPRESSEDTEXIMAGE3DARBPROC glCompressedTexImage3DARB = 0;
PFNGLCOMPRESSEDTEXIMAGE2DARBPROC glCompressedTexImage2DARB = 0;
PFNGLCOMPRESSEDTEXIMAGE1DARBPROC glCompressedTexImage1DARB = 0;
PFNGLCOMPRESSEDTEXSUBIMAGE3DARBPROC glCompressedTexSubImage3DARB = 0;
PFNGLCOMPRESSEDTEXSUBIMAGE2DARBPROC glCompressedTexSubImage2DARB = 0;
PFNGLCOMPRESSEDTEXSUBIMAGE1DARBPROC glCompressedTexSubImage1DARB = 0;
PFNGLGETCOMPRESSEDTEXIMAGEARBPROC glGetCompressedTexImageARB = 0;
#endif
#ifdef SAGE_GL_EXT_abgr
#endif
#ifdef SAGE_GL_EXT_blend_color
PFNGLBLENDCOLOREXTPROC glBlendColorEXT = 0;
#endif
#ifdef SAGE_GL_EXT_polygon_offset
PFNGLPOLYGONOFFSETEXTPROC glPolygonOffsetEXT = 0;
#endif
#ifdef SAGE_GL_EXT_texture
#endif
#ifdef SAGE_GL_EXT_texture3D
PFNGLTEXIMAGE3DEXTPROC glTexImage3DEXT = 0;
PFNGLTEXSUBIMAGE3DEXTPROC glTexSubImage3DEXT = 0;
#endif
#ifdef SAGE_GL_SGIS_texture_filter4
PFNGLGETTEXFILTERFUNCSGISPROC glGetTexFilterFuncSGIS = 0;
PFNGLTEXFILTERFUNCSGISPROC glTexFilterFuncSGIS = 0;
#endif
#ifdef SAGE_GL_EXT_subtexture
PFNGLTEXSUBIMAGE1DEXTPROC glTexSubImage1DEXT = 0;
PFNGLTEXSUBIMAGE2DEXTPROC glTexSubImage2DEXT = 0;
#endif
#ifdef SAGE_GL_EXT_copy_texture
PFNGLCOPYTEXIMAGE1DEXTPROC glCopyTexImage1DEXT = 0;
PFNGLCOPYTEXIMAGE2DEXTPROC glCopyTexImage2DEXT = 0;
PFNGLCOPYTEXSUBIMAGE1DEXTPROC glCopyTexSubImage1DEXT = 0;
PFNGLCOPYTEXSUBIMAGE2DEXTPROC glCopyTexSubImage2DEXT = 0;
PFNGLCOPYTEXSUBIMAGE3DEXTPROC glCopyTexSubImage3DEXT = 0;
#endif
#ifdef SAGE_GL_EXT_histogram
PFNGLGETHISTOGRAMEXTPROC glGetHistogramEXT = 0;
PFNGLGETHISTOGRAMPARAMETERFVEXTPROC glGetHistogramParameterfvEXT = 0;
PFNGLGETHISTOGRAMPARAMETERIVEXTPROC glGetHistogramParameterivEXT = 0;
PFNGLGETMINMAXEXTPROC glGetMinmaxEXT = 0;
PFNGLGETMINMAXPARAMETERFVEXTPROC glGetMinmaxParameterfvEXT = 0;
PFNGLGETMINMAXPARAMETERIVEXTPROC glGetMinmaxParameterivEXT = 0;
PFNGLHISTOGRAMEXTPROC glHistogramEXT = 0;
PFNGLMINMAXEXTPROC glMinmaxEXT = 0;
PFNGLRESETHISTOGRAMEXTPROC glResetHistogramEXT = 0;
PFNGLRESETMINMAXEXTPROC glResetMinmaxEXT = 0;
#endif
#ifdef SAGE_GL_EXT_convolution
PFNGLCONVOLUTIONFILTER1DEXTPROC glConvolutionFilter1DEXT = 0;
PFNGLCONVOLUTIONFILTER2DEXTPROC glConvolutionFilter2DEXT = 0;
PFNGLCONVOLUTIONPARAMETERFEXTPROC glConvolutionParameterfEXT = 0;
PFNGLCONVOLUTIONPARAMETERFVEXTPROC glConvolutionParameterfvEXT = 0;
PFNGLCONVOLUTIONPARAMETERIEXTPROC glConvolutionParameteriEXT = 0;
PFNGLCONVOLUTIONPARAMETERIVEXTPROC glConvolutionParameterivEXT = 0;
PFNGLCOPYCONVOLUTIONFILTER1DEXTPROC glCopyConvolutionFilter1DEXT = 0;
PFNGLCOPYCONVOLUTIONFILTER2DEXTPROC glCopyConvolutionFilter2DEXT = 0;
PFNGLGETCONVOLUTIONFILTEREXTPROC glGetConvolutionFilterEXT = 0;
PFNGLGETCONVOLUTIONPARAMETERFVEXTPROC glGetConvolutionParameterfvEXT = 0;
PFNGLGETCONVOLUTIONPARAMETERIVEXTPROC glGetConvolutionParameterivEXT = 0;
PFNGLGETSEPARABLEFILTEREXTPROC glGetSeparableFilterEXT = 0;
PFNGLSEPARABLEFILTER2DEXTPROC glSeparableFilter2DEXT = 0;
#endif
#ifdef SAGE_GL_EXT_color_matrix
#endif
#ifdef SAGE_GL_SGI_color_table
PFNGLCOLORTABLESGIPROC glColorTableSGI = 0;
PFNGLCOLORTABLEPARAMETERFVSGIPROC glColorTableParameterfvSGI = 0;
PFNGLCOLORTABLEPARAMETERIVSGIPROC glColorTableParameterivSGI = 0;
PFNGLCOPYCOLORTABLESGIPROC glCopyColorTableSGI = 0;
PFNGLGETCOLORTABLESGIPROC glGetColorTableSGI = 0;
PFNGLGETCOLORTABLEPARAMETERFVSGIPROC glGetColorTableParameterfvSGI = 0;
PFNGLGETCOLORTABLEPARAMETERIVSGIPROC glGetColorTableParameterivSGI = 0;
#endif
#ifdef SAGE_GL_SGIX_pixel_texture
PFNGLPIXELTEXGENSGIXPROC glPixelTexGenSGIX = 0;
#endif
#ifdef SAGE_GL_SGIS_pixel_texture
PFNGLPIXELTEXGENPARAMETERISGISPROC glPixelTexGenParameteriSGIS = 0;
PFNGLPIXELTEXGENPARAMETERIVSGISPROC glPixelTexGenParameterivSGIS = 0;
PFNGLPIXELTEXGENPARAMETERFSGISPROC glPixelTexGenParameterfSGIS = 0;
PFNGLPIXELTEXGENPARAMETERFVSGISPROC glPixelTexGenParameterfvSGIS = 0;
PFNGLGETPIXELTEXGENPARAMETERIVSGISPROC glGetPixelTexGenParameterivSGIS = 0;
PFNGLGETPIXELTEXGENPARAMETERFVSGISPROC glGetPixelTexGenParameterfvSGIS = 0;
#endif
#ifdef SAGE_GL_SGIS_texture4D
PFNGLTEXIMAGE4DSGISPROC glTexImage4DSGIS = 0;
PFNGLTEXSUBIMAGE4DSGISPROC glTexSubImage4DSGIS = 0;
#endif
#ifdef SAGE_GL_SGI_texture_color_table
#endif
#ifdef SAGE_GL_EXT_cmyka
#endif
#ifdef SAGE_GL_EXT_texture_object
PFNGLARETEXTURESRESIDENTEXTPROC glAreTexturesResidentEXT = 0;
PFNGLBINDTEXTUREEXTPROC glBindTextureEXT = 0;
PFNGLDELETETEXTURESEXTPROC glDeleteTexturesEXT = 0;
PFNGLGENTEXTURESEXTPROC glGenTexturesEXT = 0;
PFNGLISTEXTUREEXTPROC glIsTextureEXT = 0;
PFNGLPRIORITIZETEXTURESEXTPROC glPrioritizeTexturesEXT = 0;
#endif
#ifdef SAGE_GL_SGIS_detail_texture
PFNGLDETAILTEXFUNCSGISPROC glDetailTexFuncSGIS = 0;
PFNGLGETDETAILTEXFUNCSGISPROC glGetDetailTexFuncSGIS = 0;
#endif
#ifdef SAGE_GL_SGIS_sharpen_texture
PFNGLSHARPENTEXFUNCSGISPROC glSharpenTexFuncSGIS = 0;
PFNGLGETSHARPENTEXFUNCSGISPROC glGetSharpenTexFuncSGIS = 0;
#endif
#ifdef SAGE_GL_EXT_packed_pixels
#endif
#ifdef SAGE_GL_SGIS_texture_lod
#endif
#ifdef SAGE_GL_SGIS_multisample
PFNGLSAMPLEMASKSGISPROC glSampleMaskSGIS = 0;
PFNGLSAMPLEPATTERNSGISPROC glSamplePatternSGIS = 0;
#endif
#ifdef SAGE_GL_EXT_rescale_normal
#endif
#ifdef SAGE_GL_EXT_vertex_array
PFNGLARRAYELEMENTEXTPROC glArrayElementEXT = 0;
PFNGLCOLORPOINTEREXTPROC glColorPointerEXT = 0;
PFNGLDRAWARRAYSEXTPROC glDrawArraysEXT = 0;
PFNGLEDGEFLAGPOINTEREXTPROC glEdgeFlagPointerEXT = 0;
PFNGLGETPOINTERVEXTPROC glGetPointervEXT = 0;
PFNGLINDEXPOINTEREXTPROC glIndexPointerEXT = 0;
PFNGLNORMALPOINTEREXTPROC glNormalPointerEXT = 0;
PFNGLTEXCOORDPOINTEREXTPROC glTexCoordPointerEXT = 0;
PFNGLVERTEXPOINTEREXTPROC glVertexPointerEXT = 0;
#endif
#ifdef SAGE_GL_EXT_misc_attribute
#endif
#ifdef SAGE_GL_SGIS_generate_mipmap
#endif
#ifdef SAGE_GL_SGIX_clipmap
#endif
#ifdef SAGE_GL_SGIX_shadow
#endif
#ifdef SAGE_GL_SGIS_texture_edge_clamp
#endif
#ifdef SAGE_GL_SGIS_texture_border_clamp
#endif
#ifdef SAGE_GL_EXT_blend_minmax
PFNGLBLENDEQUATIONEXTPROC glBlendEquationEXT = 0;
#endif
#ifdef SAGE_GL_EXT_blend_subtract
#endif
#ifdef SAGE_GL_EXT_blend_logic_op
#endif
#ifdef SAGE_GL_SGIX_interlace
#endif
#ifdef SAGE_GL_SGIX_pixel_tiles
#endif
#ifdef SAGE_GL_SGIX_texture_select
#endif
#ifdef SAGE_GL_SGIX_sprite
PFNGLSPRITEPARAMETERFSGIXPROC glSpriteParameterfSGIX = 0;
PFNGLSPRITEPARAMETERFVSGIXPROC glSpriteParameterfvSGIX = 0;
PFNGLSPRITEPARAMETERISGIXPROC glSpriteParameteriSGIX = 0;
PFNGLSPRITEPARAMETERIVSGIXPROC glSpriteParameterivSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_texture_multi_buffer
#endif
#ifdef SAGE_GL_EXT_point_parameters
PFNGLPOINTPARAMETERFEXTPROC glPointParameterfEXT = 0;
PFNGLPOINTPARAMETERFVEXTPROC glPointParameterfvEXT = 0;
PFNGLPOINTPARAMETERFSGISPROC glPointParameterfSGIS = 0;
PFNGLPOINTPARAMETERFVSGISPROC glPointParameterfvSGIS = 0;
#endif
#ifdef SAGE_GL_SGIX_instruments
PFNGLGETINSTRUMENTSSGIXPROC glGetInstrumentsSGIX = 0;
PFNGLINSTRUMENTSBUFFERSGIXPROC glInstrumentsBufferSGIX = 0;
PFNGLPOLLINSTRUMENTSSGIXPROC glPollInstrumentsSGIX = 0;
PFNGLREADINSTRUMENTSSGIXPROC glReadInstrumentsSGIX = 0;
PFNGLSTARTINSTRUMENTSSGIXPROC glStartInstrumentsSGIX = 0;
PFNGLSTOPINSTRUMENTSSGIXPROC glStopInstrumentsSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_texture_scale_bias
#endif
#ifdef SAGE_GL_SGIX_framezoom
PFNGLFRAMEZOOMSGIXPROC glFrameZoomSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_tag_sample_buffer
PFNGLTAGSAMPLEBUFFERSGIXPROC glTagSampleBufferSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_polynomial_ffd
PFNGLDEFORMATIONMAP3DSGIXPROC glDeformationMap3dSGIX = 0;
PFNGLDEFORMATIONMAP3FSGIXPROC glDeformationMap3fSGIX = 0;
PFNGLDEFORMSGIXPROC glDeformSGIX = 0;
PFNGLLOADIDENTITYDEFORMATIONMAPSGIXPROC glLoadIdentityDeformationMapSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_reference_plane
PFNGLREFERENCEPLANESGIXPROC glReferencePlaneSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_flush_raster
PFNGLFLUSHRASTERSGIXPROC glFlushRasterSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_depth_texture
#endif
#ifdef SAGE_GL_SGIS_fog_function
PFNGLFOGFUNCSGISPROC glFogFuncSGIS = 0;
PFNGLGETFOGFUNCSGISPROC glGetFogFuncSGIS = 0;
#endif
#ifdef SAGE_GL_SGIX_fog_offset
#endif
#ifdef SAGE_GL_HP_image_transform
PFNGLIMAGETRANSFORMPARAMETERIHPPROC glImageTransformParameteriHP = 0;
PFNGLIMAGETRANSFORMPARAMETERFHPPROC glImageTransformParameterfHP = 0;
PFNGLIMAGETRANSFORMPARAMETERIVHPPROC glImageTransformParameterivHP = 0;
PFNGLIMAGETRANSFORMPARAMETERFVHPPROC glImageTransformParameterfvHP = 0;
PFNGLGETIMAGETRANSFORMPARAMETERIVHPPROC glGetImageTransformParameterivHP = 0;
PFNGLGETIMAGETRANSFORMPARAMETERFVHPPROC glGetImageTransformParameterfvHP = 0;
#endif
#ifdef SAGE_GL_HP_convolution_border_modes
#endif
#ifdef SAGE_GL_SGIX_texture_add_env
#endif
#ifdef SAGE_GL_EXT_color_subtable
PFNGLCOLORSUBTABLEEXTPROC glColorSubTableEXT = 0;
PFNGLCOPYCOLORSUBTABLEEXTPROC glCopyColorSubTableEXT = 0;
#endif
#ifdef SAGE_GL_PGI_vertex_hints
#endif
#ifdef SAGE_GL_PGI_misc_hints
PFNGLHINTPGIPROC glHintPGI = 0;
#endif
#ifdef SAGE_GL_EXT_paletted_texture
PFNGLCOLORTABLEEXTPROC glColorTableEXT = 0;
PFNGLGETCOLORTABLEEXTPROC glGetColorTableEXT = 0;
PFNGLGETCOLORTABLEPARAMETERIVEXTPROC glGetColorTableParameterivEXT = 0;
PFNGLGETCOLORTABLEPARAMETERFVEXTPROC glGetColorTableParameterfvEXT = 0;
#endif
#ifdef SAGE_GL_EXT_clip_volume_hint
#endif
#ifdef SAGE_GL_SGIX_list_priority
PFNGLGETLISTPARAMETERFVSGIXPROC glGetListParameterfvSGIX = 0;
PFNGLGETLISTPARAMETERIVSGIXPROC glGetListParameterivSGIX = 0;
PFNGLLISTPARAMETERFSGIXPROC glListParameterfSGIX = 0;
PFNGLLISTPARAMETERFVSGIXPROC glListParameterfvSGIX = 0;
PFNGLLISTPARAMETERISGIXPROC glListParameteriSGIX = 0;
PFNGLLISTPARAMETERIVSGIXPROC glListParameterivSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_ir_instrument1
#endif
#ifdef SAGE_GL_SGIX_calligraphic_fragment
#endif
#ifdef SAGE_GL_SGIX_texture_lod_bias
#endif
#ifdef SAGE_GL_SGIX_shadow_ambient
#endif
#ifdef SAGE_GL_EXT_index_texture
#endif
#ifdef SAGE_GL_EXT_index_material
PFNGLINDEXMATERIALEXTPROC glIndexMaterialEXT = 0;
#endif
#ifdef SAGE_GL_EXT_index_func
PFNGLINDEXFUNCEXTPROC glIndexFuncEXT = 0;
#endif
#ifdef SAGE_GL_EXT_index_array_formats
#endif
#ifdef SAGE_GL_EXT_compiled_vertex_array
PFNGLLOCKARRAYSEXTPROC glLockArraysEXT = 0;
PFNGLUNLOCKARRAYSEXTPROC glUnlockArraysEXT = 0;
#endif
#ifdef SAGE_GL_EXT_cull_vertex
PFNGLCULLPARAMETERDVEXTPROC glCullParameterdvEXT = 0;
PFNGLCULLPARAMETERFVEXTPROC glCullParameterfvEXT = 0;
#endif
#ifdef SAGE_GL_SGIX_ycrcb
#endif
#ifdef SAGE_GL_SGIX_fragment_lighting
PFNGLFRAGMENTCOLORMATERIALSGIXPROC glFragmentColorMaterialSGIX = 0;
PFNGLFRAGMENTLIGHTFSGIXPROC glFragmentLightfSGIX = 0;
PFNGLFRAGMENTLIGHTFVSGIXPROC glFragmentLightfvSGIX = 0;
PFNGLFRAGMENTLIGHTISGIXPROC glFragmentLightiSGIX = 0;
PFNGLFRAGMENTLIGHTIVSGIXPROC glFragmentLightivSGIX = 0;
PFNGLFRAGMENTLIGHTMODELFSGIXPROC glFragmentLightModelfSGIX = 0;
PFNGLFRAGMENTLIGHTMODELFVSGIXPROC glFragmentLightModelfvSGIX = 0;
PFNGLFRAGMENTLIGHTMODELISGIXPROC glFragmentLightModeliSGIX = 0;
PFNGLFRAGMENTLIGHTMODELIVSGIXPROC glFragmentLightModelivSGIX = 0;
PFNGLFRAGMENTMATERIALFSGIXPROC glFragmentMaterialfSGIX = 0;
PFNGLFRAGMENTMATERIALFVSGIXPROC glFragmentMaterialfvSGIX = 0;
PFNGLFRAGMENTMATERIALISGIXPROC glFragmentMaterialiSGIX = 0;
PFNGLFRAGMENTMATERIALIVSGIXPROC glFragmentMaterialivSGIX = 0;
PFNGLGETFRAGMENTLIGHTFVSGIXPROC glGetFragmentLightfvSGIX = 0;
PFNGLGETFRAGMENTLIGHTIVSGIXPROC glGetFragmentLightivSGIX = 0;
PFNGLGETFRAGMENTMATERIALFVSGIXPROC glGetFragmentMaterialfvSGIX = 0;
PFNGLGETFRAGMENTMATERIALIVSGIXPROC glGetFragmentMaterialivSGIX = 0;
PFNGLLIGHTENVISGIXPROC glLightEnviSGIX = 0;
#endif
#ifdef SAGE_GL_IBM_rasterpos_clip
#endif
#ifdef SAGE_GL_HP_texture_lighting
#endif
#ifdef SAGE_GL_EXT_draw_range_elements
PFNGLDRAWRANGEELEMENTSEXTPROC glDrawRangeElementsEXT = 0;
#endif
#ifdef SAGE_GL_WIN_phong_shading
#endif
#ifdef SAGE_GL_WIN_specular_fog
#endif
#ifdef SAGE_GL_EXT_light_texture
PFNGLAPPLYTEXTUREEXTPROC glApplyTextureEXT = 0;
PFNGLTEXTURELIGHTEXTPROC glTextureLightEXT = 0;
PFNGLTEXTUREMATERIALEXTPROC glTextureMaterialEXT = 0;
#endif
#ifdef SAGE_GL_SGIX_blend_alpha_minmax
#endif
#ifdef SAGE_GL_EXT_bgra
#endif
#ifdef SAGE_GL_SGIX_async
PFNGLASYNCMARKERSGIXPROC glAsyncMarkerSGIX = 0;
PFNGLFINISHASYNCSGIXPROC glFinishAsyncSGIX = 0;
PFNGLPOLLASYNCSGIXPROC glPollAsyncSGIX = 0;
PFNGLGENASYNCMARKERSSGIXPROC glGenAsyncMarkersSGIX = 0;
PFNGLDELETEASYNCMARKERSSGIXPROC glDeleteAsyncMarkersSGIX = 0;
PFNGLISASYNCMARKERSGIXPROC glIsAsyncMarkerSGIX = 0;
#endif
#ifdef SAGE_GL_SGIX_async_pixel
#endif
#ifdef SAGE_GL_SGIX_async_histogram
#endif
#ifdef SAGE_GL_INTEL_parallel_arrays
PFNGLVERTEXPOINTERVINTELPROC glVertexPointervINTEL = 0;
PFNGLNORMALPOINTERVINTELPROC glNormalPointervINTEL = 0;
PFNGLCOLORPOINTERVINTELPROC glColorPointervINTEL = 0;
PFNGLTEXCOORDPOINTERVINTELPROC glTexCoordPointervINTEL = 0;
#endif
#ifdef SAGE_GL_HP_occlusion_test
#endif
#ifdef SAGE_GL_EXT_pixel_transform
PFNGLPIXELTRANSFORMPARAMETERIEXTPROC glPixelTransformParameteriEXT = 0;
PFNGLPIXELTRANSFORMPARAMETERFEXTPROC glPixelTransformParameterfEXT = 0;
PFNGLPIXELTRANSFORMPARAMETERIVEXTPROC glPixelTransformParameterivEXT = 0;
PFNGLPIXELTRANSFORMPARAMETERFVEXTPROC glPixelTransformParameterfvEXT = 0;
#endif
#ifdef SAGE_GL_EXT_pixel_transform_color_table
#endif
#ifdef SAGE_GL_EXT_shared_texture_palette
#endif
#ifdef SAGE_GL_EXT_separate_specular_color
#endif
#ifdef SAGE_GL_EXT_secondary_color
PFNGLSECONDARYCOLOR3BEXTPROC glSecondaryColor3bEXT = 0;
PFNGLSECONDARYCOLOR3BVEXTPROC glSecondaryColor3bvEXT = 0;
PFNGLSECONDARYCOLOR3DEXTPROC glSecondaryColor3dEXT = 0;
PFNGLSECONDARYCOLOR3DVEXTPROC glSecondaryColor3dvEXT = 0;
PFNGLSECONDARYCOLOR3FEXTPROC glSecondaryColor3fEXT = 0;
PFNGLSECONDARYCOLOR3FVEXTPROC glSecondaryColor3fvEXT = 0;
PFNGLSECONDARYCOLOR3IEXTPROC glSecondaryColor3iEXT = 0;
PFNGLSECONDARYCOLOR3IVEXTPROC glSecondaryColor3ivEXT = 0;
PFNGLSECONDARYCOLOR3SEXTPROC glSecondaryColor3sEXT = 0;
PFNGLSECONDARYCOLOR3SVEXTPROC glSecondaryColor3svEXT = 0;
PFNGLSECONDARYCOLOR3UBEXTPROC glSecondaryColor3ubEXT = 0;
PFNGLSECONDARYCOLOR3UBVEXTPROC glSecondaryColor3ubvEXT = 0;
PFNGLSECONDARYCOLOR3UIEXTPROC glSecondaryColor3uiEXT = 0;
PFNGLSECONDARYCOLOR3UIVEXTPROC glSecondaryColor3uivEXT = 0;
PFNGLSECONDARYCOLOR3USEXTPROC glSecondaryColor3usEXT = 0;
PFNGLSECONDARYCOLOR3USVEXTPROC glSecondaryColor3usvEXT = 0;
PFNGLSECONDARYCOLORPOINTEREXTPROC glSecondaryColorPointerEXT = 0;
#endif
#ifdef SAGE_GL_EXT_texture_perturb_normal
PFNGLTEXTURENORMALEXTPROC glTextureNormalEXT = 0;
#endif
#ifdef SAGE_GL_EXT_multi_draw_arrays
PFNGLMULTIDRAWARRAYSEXTPROC glMultiDrawArraysEXT = 0;
PFNGLMULTIDRAWELEMENTSEXTPROC glMultiDrawElementsEXT = 0;
#endif
#ifdef SAGE_GL_EXT_fog_coord
PFNGLFOGCOORDFEXTPROC glFogCoordfEXT = 0;
PFNGLFOGCOORDFVEXTPROC glFogCoordfvEXT = 0;
PFNGLFOGCOORDDEXTPROC glFogCoorddEXT = 0;
PFNGLFOGCOORDDVEXTPROC glFogCoorddvEXT = 0;
PFNGLFOGCOORDPOINTEREXTPROC glFogCoordPointerEXT = 0;
#endif
#ifdef SAGE_GL_REND_screen_coordinates
#endif
#ifdef SAGE_GL_EXT_coordinate_frame
PFNGLTANGENT3BEXTPROC glTangent3bEXT = 0;
PFNGLTANGENT3BVEXTPROC glTangent3bvEXT = 0;
PFNGLTANGENT3DEXTPROC glTangent3dEXT = 0;
PFNGLTANGENT3DVEXTPROC glTangent3dvEXT = 0;
PFNGLTANGENT3FEXTPROC glTangent3fEXT = 0;
PFNGLTANGENT3FVEXTPROC glTangent3fvEXT = 0;
PFNGLTANGENT3IEXTPROC glTangent3iEXT = 0;
PFNGLTANGENT3IVEXTPROC glTangent3ivEXT = 0;
PFNGLTANGENT3SEXTPROC glTangent3sEXT = 0;
PFNGLTANGENT3SVEXTPROC glTangent3svEXT = 0;
PFNGLBINORMAL3BEXTPROC glBinormal3bEXT = 0;
PFNGLBINORMAL3BVEXTPROC glBinormal3bvEXT = 0;
PFNGLBINORMAL3DEXTPROC glBinormal3dEXT = 0;
PFNGLBINORMAL3DVEXTPROC glBinormal3dvEXT = 0;
PFNGLBINORMAL3FEXTPROC glBinormal3fEXT = 0;
PFNGLBINORMAL3FVEXTPROC glBinormal3fvEXT = 0;
PFNGLBINORMAL3IEXTPROC glBinormal3iEXT = 0;
PFNGLBINORMAL3IVEXTPROC glBinormal3ivEXT = 0;
PFNGLBINORMAL3SEXTPROC glBinormal3sEXT = 0;
PFNGLBINORMAL3SVEXTPROC glBinormal3svEXT = 0;
PFNGLTANGENTPOINTEREXTPROC glTangentPointerEXT = 0;
PFNGLBINORMALPOINTEREXTPROC glBinormalPointerEXT = 0;
#endif
#ifdef SAGE_GL_EXT_texture_env_combine
#endif
#ifdef SAGE_GL_APPLE_specular_vector
#endif
#ifdef SAGE_GL_APPLE_transform_hint
#endif
#ifdef SAGE_GL_SGIX_fog_scale
#endif
#ifdef SAGE_GL_SUNX_constant_data
PFNGLFINISHTEXTURESUNXPROC glFinishTextureSUNX = 0;
#endif
#ifdef SAGE_GL_SUN_global_alpha
PFNGLGLOBALALPHAFACTORBSUNPROC glGlobalAlphaFactorbSUN = 0;
PFNGLGLOBALALPHAFACTORSSUNPROC glGlobalAlphaFactorsSUN = 0;
PFNGLGLOBALALPHAFACTORISUNPROC glGlobalAlphaFactoriSUN = 0;
PFNGLGLOBALALPHAFACTORFSUNPROC glGlobalAlphaFactorfSUN = 0;
PFNGLGLOBALALPHAFACTORDSUNPROC glGlobalAlphaFactordSUN = 0;
PFNGLGLOBALALPHAFACTORUBSUNPROC glGlobalAlphaFactorubSUN = 0;
PFNGLGLOBALALPHAFACTORUSSUNPROC glGlobalAlphaFactorusSUN = 0;
PFNGLGLOBALALPHAFACTORUISUNPROC glGlobalAlphaFactoruiSUN = 0;
#endif
#ifdef SAGE_GL_SUN_triangle_list
PFNGLREPLACEMENTCODEUISUNPROC glReplacementCodeuiSUN = 0;
PFNGLREPLACEMENTCODEUSSUNPROC glReplacementCodeusSUN = 0;
PFNGLREPLACEMENTCODEUBSUNPROC glReplacementCodeubSUN = 0;
PFNGLREPLACEMENTCODEUIVSUNPROC glReplacementCodeuivSUN = 0;
PFNGLREPLACEMENTCODEUSVSUNPROC glReplacementCodeusvSUN = 0;
PFNGLREPLACEMENTCODEUBVSUNPROC glReplacementCodeubvSUN = 0;
PFNGLREPLACEMENTCODEPOINTERSUNPROC glReplacementCodePointerSUN = 0;
#endif
#ifdef SAGE_GL_SUN_vertex
PFNGLCOLOR4UBVERTEX2FSUNPROC glColor4ubVertex2fSUN = 0;
PFNGLCOLOR4UBVERTEX2FVSUNPROC glColor4ubVertex2fvSUN = 0;
PFNGLCOLOR4UBVERTEX3FSUNPROC glColor4ubVertex3fSUN = 0;
PFNGLCOLOR4UBVERTEX3FVSUNPROC glColor4ubVertex3fvSUN = 0;
PFNGLCOLOR3FVERTEX3FSUNPROC glColor3fVertex3fSUN = 0;
PFNGLCOLOR3FVERTEX3FVSUNPROC glColor3fVertex3fvSUN = 0;
PFNGLNORMAL3FVERTEX3FSUNPROC glNormal3fVertex3fSUN = 0;
PFNGLNORMAL3FVERTEX3FVSUNPROC glNormal3fVertex3fvSUN = 0;
PFNGLCOLOR4FNORMAL3FVERTEX3FSUNPROC glColor4fNormal3fVertex3fSUN = 0;
PFNGLCOLOR4FNORMAL3FVERTEX3FVSUNPROC glColor4fNormal3fVertex3fvSUN = 0;
PFNGLTEXCOORD2FVERTEX3FSUNPROC glTexCoord2fVertex3fSUN = 0;
PFNGLTEXCOORD2FVERTEX3FVSUNPROC glTexCoord2fVertex3fvSUN = 0;
PFNGLTEXCOORD4FVERTEX4FSUNPROC glTexCoord4fVertex4fSUN = 0;
PFNGLTEXCOORD4FVERTEX4FVSUNPROC glTexCoord4fVertex4fvSUN = 0;
PFNGLTEXCOORD2FCOLOR4UBVERTEX3FSUNPROC glTexCoord2fColor4ubVertex3fSUN = 0;
PFNGLTEXCOORD2FCOLOR4UBVERTEX3FVSUNPROC glTexCoord2fColor4ubVertex3fvSUN = 0;
PFNGLTEXCOORD2FCOLOR3FVERTEX3FSUNPROC glTexCoord2fColor3fVertex3fSUN = 0;
PFNGLTEXCOORD2FCOLOR3FVERTEX3FVSUNPROC glTexCoord2fColor3fVertex3fvSUN = 0;
PFNGLTEXCOORD2FNORMAL3FVERTEX3FSUNPROC glTexCoord2fNormal3fVertex3fSUN = 0;
PFNGLTEXCOORD2FNORMAL3FVERTEX3FVSUNPROC glTexCoord2fNormal3fVertex3fvSUN = 0;
PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC glTexCoord2fColor4fNormal3fVertex3fSUN = 0;
PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC glTexCoord2fColor4fNormal3fVertex3fvSUN = 0;
PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FSUNPROC glTexCoord4fColor4fNormal3fVertex4fSUN = 0;
PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FVSUNPROC glTexCoord4fColor4fNormal3fVertex4fvSUN = 0;
PFNGLREPLACEMENTCODEUIVERTEX3FSUNPROC glReplacementCodeuiVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUIVERTEX3FVSUNPROC glReplacementCodeuiVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FSUNPROC glReplacementCodeuiColor4ubVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FVSUNPROC glReplacementCodeuiColor4ubVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FSUNPROC glReplacementCodeuiColor3fVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FVSUNPROC glReplacementCodeuiColor3fVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FSUNPROC glReplacementCodeuiNormal3fVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FVSUNPROC glReplacementCodeuiNormal3fVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FSUNPROC glReplacementCodeuiColor4fNormal3fVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FVSUNPROC glReplacementCodeuiColor4fNormal3fVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FSUNPROC glReplacementCodeuiTexCoord2fVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FVSUNPROC glReplacementCodeuiTexCoord2fVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FSUNPROC glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FVSUNPROC glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN = 0;
PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN = 0;
PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN = 0;
#endif
#ifdef SAGE_GL_EXT_blend_func_separate
PFNGLBLENDFUNCSEPARATEEXTPROC glBlendFuncSeparateEXT = 0;
#endif
#ifdef SAGE_GL_INGR_color_clamp
#endif
#ifdef SAGE_GL_INGR_interlace_read
#endif
#ifdef SAGE_GL_EXT_stencil_wrap
#endif
#ifdef SAGE_GL_EXT_422_pixels
#endif
#ifdef SAGE_GL_NV_texgen_reflection
#endif
#ifdef SAGE_GL_SUN_convolution_border_modes
#endif
#ifdef SAGE_GL_EXT_texture_env_add
#endif
#ifdef SAGE_GL_EXT_texture_lod_bias
#endif
#ifdef SAGE_GL_EXT_texture_filter_anisotropic
#endif
#ifdef SAGE_GL_EXT_vertex_weighting
PFNGLVERTEXWEIGHTFEXTPROC glVertexWeightfEXT = 0;
PFNGLVERTEXWEIGHTFVEXTPROC glVertexWeightfvEXT = 0;
PFNGLVERTEXWEIGHTPOINTEREXTPROC glVertexWeightPointerEXT = 0;
#endif
#ifdef SAGE_GL_NV_light_max_exponent
#endif
#ifdef SAGE_GL_NV_vertex_array_range
PFNGLFLUSHVERTEXARRAYRANGENVPROC glFlushVertexArrayRangeNV = 0;
PFNGLVERTEXARRAYRANGENVPROC glVertexArrayRangeNV = 0;
#endif
#ifdef SAGE_GL_NV_register_combiners
PFNGLCOMBINERPARAMETERFVNVPROC glCombinerParameterfvNV = 0;
PFNGLCOMBINERPARAMETERFNVPROC glCombinerParameterfNV = 0;
PFNGLCOMBINERPARAMETERIVNVPROC glCombinerParameterivNV = 0;
PFNGLCOMBINERPARAMETERINVPROC glCombinerParameteriNV = 0;
PFNGLCOMBINERINPUTNVPROC glCombinerInputNV = 0;
PFNGLCOMBINEROUTPUTNVPROC glCombinerOutputNV = 0;
PFNGLFINALCOMBINERINPUTNVPROC glFinalCombinerInputNV = 0;
PFNGLGETCOMBINERINPUTPARAMETERFVNVPROC glGetCombinerInputParameterfvNV = 0;
PFNGLGETCOMBINERINPUTPARAMETERIVNVPROC glGetCombinerInputParameterivNV = 0;
PFNGLGETCOMBINEROUTPUTPARAMETERFVNVPROC glGetCombinerOutputParameterfvNV = 0;
PFNGLGETCOMBINEROUTPUTPARAMETERIVNVPROC glGetCombinerOutputParameterivNV = 0;
PFNGLGETFINALCOMBINERINPUTPARAMETERFVNVPROC glGetFinalCombinerInputParameterfvNV = 0;
PFNGLGETFINALCOMBINERINPUTPARAMETERIVNVPROC glGetFinalCombinerInputParameterivNV = 0;
#endif
#ifdef SAGE_GL_NV_fog_distance
#endif
#ifdef SAGE_GL_NV_texgen_emboss
#endif
#ifdef SAGE_GL_NV_blend_square
#endif
#ifdef SAGE_GL_NV_texture_env_combine4
#endif
#ifdef SAGE_GL_MESA_resize_buffers
PFNGLRESIZEBUFFERSMESAPROC glResizeBuffersMESA = 0;
#endif
#ifdef SAGE_GL_MESA_window_pos
PFNGLWINDOWPOS2DMESAPROC glWindowPos2dMESA = 0;
PFNGLWINDOWPOS2DVMESAPROC glWindowPos2dvMESA = 0;
PFNGLWINDOWPOS2FMESAPROC glWindowPos2fMESA = 0;
PFNGLWINDOWPOS2FVMESAPROC glWindowPos2fvMESA = 0;
PFNGLWINDOWPOS2IMESAPROC glWindowPos2iMESA = 0;
PFNGLWINDOWPOS2IVMESAPROC glWindowPos2ivMESA = 0;
PFNGLWINDOWPOS2SMESAPROC glWindowPos2sMESA = 0;
PFNGLWINDOWPOS2SVMESAPROC glWindowPos2svMESA = 0;
PFNGLWINDOWPOS3DMESAPROC glWindowPos3dMESA = 0;
PFNGLWINDOWPOS3DVMESAPROC glWindowPos3dvMESA = 0;
PFNGLWINDOWPOS3FMESAPROC glWindowPos3fMESA = 0;
PFNGLWINDOWPOS3FVMESAPROC glWindowPos3fvMESA = 0;
PFNGLWINDOWPOS3IMESAPROC glWindowPos3iMESA = 0;
PFNGLWINDOWPOS3IVMESAPROC glWindowPos3ivMESA = 0;
PFNGLWINDOWPOS3SMESAPROC glWindowPos3sMESA = 0;
PFNGLWINDOWPOS3SVMESAPROC glWindowPos3svMESA = 0;
PFNGLWINDOWPOS4DMESAPROC glWindowPos4dMESA = 0;
PFNGLWINDOWPOS4DVMESAPROC glWindowPos4dvMESA = 0;
PFNGLWINDOWPOS4FMESAPROC glWindowPos4fMESA = 0;
PFNGLWINDOWPOS4FVMESAPROC glWindowPos4fvMESA = 0;
PFNGLWINDOWPOS4IMESAPROC glWindowPos4iMESA = 0;
PFNGLWINDOWPOS4IVMESAPROC glWindowPos4ivMESA = 0;
PFNGLWINDOWPOS4SMESAPROC glWindowPos4sMESA = 0;
PFNGLWINDOWPOS4SVMESAPROC glWindowPos4svMESA = 0;
#endif
#ifdef SAGE_GL_IBM_cull_vertex
#endif
#ifdef SAGE_GL_IBM_multimode_draw_arrays
PFNGLMULTIMODEDRAWARRAYSIBMPROC glMultiModeDrawArraysIBM = 0;
PFNGLMULTIMODEDRAWELEMENTSIBMPROC glMultiModeDrawElementsIBM = 0;
#endif
#ifdef SAGE_GL_IBM_vertex_array_lists
PFNGLCOLORPOINTERLISTIBMPROC glColorPointerListIBM = 0;
PFNGLSECONDARYCOLORPOINTERLISTIBMPROC glSecondaryColorPointerListIBM = 0;
PFNGLEDGEFLAGPOINTERLISTIBMPROC glEdgeFlagPointerListIBM = 0;
PFNGLFOGCOORDPOINTERLISTIBMPROC glFogCoordPointerListIBM = 0;
PFNGLINDEXPOINTERLISTIBMPROC glIndexPointerListIBM = 0;
PFNGLNORMALPOINTERLISTIBMPROC glNormalPointerListIBM = 0;
PFNGLTEXCOORDPOINTERLISTIBMPROC glTexCoordPointerListIBM = 0;
PFNGLVERTEXPOINTERLISTIBMPROC glVertexPointerListIBM = 0;
#endif
#ifdef SAGE_GL_SGIX_subsample
#endif
#ifdef SAGE_GL_SGIX_ycrcba
#endif
#ifdef SAGE_GL_SGIX_ycrcb_subsample
#endif
#ifdef SAGE_GL_SGIX_depth_pass_instrument
#endif
#ifdef SAGE_GL_3DFX_texture_compression_FXT1
#endif
#ifdef SAGE_GL_3DFX_multisample
#endif
#ifdef SAGE_GL_3DFX_tbuffer
PFNGLTBUFFERMASK3DFXPROC glTbufferMask3DFX = 0;
#endif
#ifdef SAGE_GL_EXT_multisample
PFNGLSAMPLEMASKEXTPROC glSampleMaskEXT = 0;
PFNGLSAMPLEPATTERNEXTPROC glSamplePatternEXT = 0;
#endif
#ifdef SAGE_GL_SGI_vertex_preclip
#endif
#ifdef SAGE_GL_SGIX_convolution_accuracy
#endif
#ifdef SAGE_GL_SGIX_resample
#endif
#ifdef SAGE_GL_SGIS_point_line_texgen
#endif
#ifdef SAGE_GL_SGIS_texture_color_mask
PFNGLTEXTURECOLORMASKSGISPROC glTextureColorMaskSGIS = 0;
#endif
#ifdef SAGE_GL_SGIX_igloo_interface
PFNGLIGLOOINTERFACESGIXPROC glIglooInterfaceSGIX = 0;
#endif
#ifdef SAGE_GL_EXT_texture_env_dot3
#endif

void sage_init(void) {
#ifdef SAGE_GL_VERSION_1_2
  glBlendColor = (PFNGLBLENDCOLORPROC)SDL_GL_GetProcAddress("glBlendColor");
  glBlendEquation = (PFNGLBLENDEQUATIONPROC)SDL_GL_GetProcAddress("glBlendEquation");
  glDrawRangeElements = (PFNGLDRAWRANGEELEMENTSPROC)SDL_GL_GetProcAddress("glDrawRangeElements");
  glColorTable = (PFNGLCOLORTABLEPROC)SDL_GL_GetProcAddress("glColorTable");
  glColorTableParameterfv = (PFNGLCOLORTABLEPARAMETERFVPROC)SDL_GL_GetProcAddress("glColorTableParameterfv");
  glColorTableParameteriv = (PFNGLCOLORTABLEPARAMETERIVPROC)SDL_GL_GetProcAddress("glColorTableParameteriv");
  glCopyColorTable = (PFNGLCOPYCOLORTABLEPROC)SDL_GL_GetProcAddress("glCopyColorTable");
  glGetColorTable = (PFNGLGETCOLORTABLEPROC)SDL_GL_GetProcAddress("glGetColorTable");
  glGetColorTableParameterfv = (PFNGLGETCOLORTABLEPARAMETERFVPROC)SDL_GL_GetProcAddress("glGetColorTableParameterfv");
  glGetColorTableParameteriv = (PFNGLGETCOLORTABLEPARAMETERIVPROC)SDL_GL_GetProcAddress("glGetColorTableParameteriv");
  glColorSubTable = (PFNGLCOLORSUBTABLEPROC)SDL_GL_GetProcAddress("glColorSubTable");
  glCopyColorSubTable = (PFNGLCOPYCOLORSUBTABLEPROC)SDL_GL_GetProcAddress("glCopyColorSubTable");
  glConvolutionFilter1D = (PFNGLCONVOLUTIONFILTER1DPROC)SDL_GL_GetProcAddress("glConvolutionFilter1D");
  glConvolutionFilter2D = (PFNGLCONVOLUTIONFILTER2DPROC)SDL_GL_GetProcAddress("glConvolutionFilter2D");
  glConvolutionParameterf = (PFNGLCONVOLUTIONPARAMETERFPROC)SDL_GL_GetProcAddress("glConvolutionParameterf");
  glConvolutionParameterfv = (PFNGLCONVOLUTIONPARAMETERFVPROC)SDL_GL_GetProcAddress("glConvolutionParameterfv");
  glConvolutionParameteri = (PFNGLCONVOLUTIONPARAMETERIPROC)SDL_GL_GetProcAddress("glConvolutionParameteri");
  glConvolutionParameteriv = (PFNGLCONVOLUTIONPARAMETERIVPROC)SDL_GL_GetProcAddress("glConvolutionParameteriv");
  glCopyConvolutionFilter1D = (PFNGLCOPYCONVOLUTIONFILTER1DPROC)SDL_GL_GetProcAddress("glCopyConvolutionFilter1D");
  glCopyConvolutionFilter2D = (PFNGLCOPYCONVOLUTIONFILTER2DPROC)SDL_GL_GetProcAddress("glCopyConvolutionFilter2D");
  glGetConvolutionFilter = (PFNGLGETCONVOLUTIONFILTERPROC)SDL_GL_GetProcAddress("glGetConvolutionFilter");
  glGetConvolutionParameterfv = (PFNGLGETCONVOLUTIONPARAMETERFVPROC)SDL_GL_GetProcAddress("glGetConvolutionParameterfv");
  glGetConvolutionParameteriv = (PFNGLGETCONVOLUTIONPARAMETERIVPROC)SDL_GL_GetProcAddress("glGetConvolutionParameteriv");
  glGetSeparableFilter = (PFNGLGETSEPARABLEFILTERPROC)SDL_GL_GetProcAddress("glGetSeparableFilter");
  glSeparableFilter2D = (PFNGLSEPARABLEFILTER2DPROC)SDL_GL_GetProcAddress("glSeparableFilter2D");
  glGetHistogram = (PFNGLGETHISTOGRAMPROC)SDL_GL_GetProcAddress("glGetHistogram");
  glGetHistogramParameterfv = (PFNGLGETHISTOGRAMPARAMETERFVPROC)SDL_GL_GetProcAddress("glGetHistogramParameterfv");
  glGetHistogramParameteriv = (PFNGLGETHISTOGRAMPARAMETERIVPROC)SDL_GL_GetProcAddress("glGetHistogramParameteriv");
  glGetMinmax = (PFNGLGETMINMAXPROC)SDL_GL_GetProcAddress("glGetMinmax");
  glGetMinmaxParameterfv = (PFNGLGETMINMAXPARAMETERFVPROC)SDL_GL_GetProcAddress("glGetMinmaxParameterfv");
  glGetMinmaxParameteriv = (PFNGLGETMINMAXPARAMETERIVPROC)SDL_GL_GetProcAddress("glGetMinmaxParameteriv");
  glHistogram = (PFNGLHISTOGRAMPROC)SDL_GL_GetProcAddress("glHistogram");
  glMinmax = (PFNGLMINMAXPROC)SDL_GL_GetProcAddress("glMinmax");
  glResetHistogram = (PFNGLRESETHISTOGRAMPROC)SDL_GL_GetProcAddress("glResetHistogram");
  glResetMinmax = (PFNGLRESETMINMAXPROC)SDL_GL_GetProcAddress("glResetMinmax");
  glTexImage3D = (PFNGLTEXIMAGE3DPROC)SDL_GL_GetProcAddress("glTexImage3D");
  glTexSubImage3D = (PFNGLTEXSUBIMAGE3DPROC)SDL_GL_GetProcAddress("glTexSubImage3D");
  glCopyTexSubImage3D = (PFNGLCOPYTEXSUBIMAGE3DPROC)SDL_GL_GetProcAddress("glCopyTexSubImage3D");
#endif
#ifdef SAGE_GL_ARB_multitexture
  glActiveTextureARB = (PFNGLACTIVETEXTUREARBPROC)SDL_GL_GetProcAddress("glActiveTextureARB");
  glClientActiveTextureARB = (PFNGLCLIENTACTIVETEXTUREARBPROC)SDL_GL_GetProcAddress("glClientActiveTextureARB");
  glMultiTexCoord1dARB = (PFNGLMULTITEXCOORD1DARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1dARB");
  glMultiTexCoord1dvARB = (PFNGLMULTITEXCOORD1DVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1dvARB");
  glMultiTexCoord1fARB = (PFNGLMULTITEXCOORD1FARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1fARB");
  glMultiTexCoord1fvARB = (PFNGLMULTITEXCOORD1FVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1fvARB");
  glMultiTexCoord1iARB = (PFNGLMULTITEXCOORD1IARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1iARB");
  glMultiTexCoord1ivARB = (PFNGLMULTITEXCOORD1IVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1ivARB");
  glMultiTexCoord1sARB = (PFNGLMULTITEXCOORD1SARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1sARB");
  glMultiTexCoord1svARB = (PFNGLMULTITEXCOORD1SVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord1svARB");
  glMultiTexCoord2dARB = (PFNGLMULTITEXCOORD2DARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2dARB");
  glMultiTexCoord2dvARB = (PFNGLMULTITEXCOORD2DVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2dvARB");
  glMultiTexCoord2fARB = (PFNGLMULTITEXCOORD2FARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2fARB");
  glMultiTexCoord2fvARB = (PFNGLMULTITEXCOORD2FVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2fvARB");
  glMultiTexCoord2iARB = (PFNGLMULTITEXCOORD2IARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2iARB");
  glMultiTexCoord2ivARB = (PFNGLMULTITEXCOORD2IVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2ivARB");
  glMultiTexCoord2sARB = (PFNGLMULTITEXCOORD2SARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2sARB");
  glMultiTexCoord2svARB = (PFNGLMULTITEXCOORD2SVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord2svARB");
  glMultiTexCoord3dARB = (PFNGLMULTITEXCOORD3DARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3dARB");
  glMultiTexCoord3dvARB = (PFNGLMULTITEXCOORD3DVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3dvARB");
  glMultiTexCoord3fARB = (PFNGLMULTITEXCOORD3FARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3fARB");
  glMultiTexCoord3fvARB = (PFNGLMULTITEXCOORD3FVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3fvARB");
  glMultiTexCoord3iARB = (PFNGLMULTITEXCOORD3IARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3iARB");
  glMultiTexCoord3ivARB = (PFNGLMULTITEXCOORD3IVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3ivARB");
  glMultiTexCoord3sARB = (PFNGLMULTITEXCOORD3SARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3sARB");
  glMultiTexCoord3svARB = (PFNGLMULTITEXCOORD3SVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord3svARB");
  glMultiTexCoord4dARB = (PFNGLMULTITEXCOORD4DARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4dARB");
  glMultiTexCoord4dvARB = (PFNGLMULTITEXCOORD4DVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4dvARB");
  glMultiTexCoord4fARB = (PFNGLMULTITEXCOORD4FARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4fARB");
  glMultiTexCoord4fvARB = (PFNGLMULTITEXCOORD4FVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4fvARB");
  glMultiTexCoord4iARB = (PFNGLMULTITEXCOORD4IARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4iARB");
  glMultiTexCoord4ivARB = (PFNGLMULTITEXCOORD4IVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4ivARB");
  glMultiTexCoord4sARB = (PFNGLMULTITEXCOORD4SARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4sARB");
  glMultiTexCoord4svARB = (PFNGLMULTITEXCOORD4SVARBPROC)SDL_GL_GetProcAddress("glMultiTexCoord4svARB");
#endif
#ifdef SAGE_GL_ARB_transpose_matrix
  glLoadTransposeMatrixfARB = (PFNGLLOADTRANSPOSEMATRIXFARBPROC)SDL_GL_GetProcAddress("glLoadTransposeMatrixfARB");
  glLoadTransposeMatrixdARB = (PFNGLLOADTRANSPOSEMATRIXDARBPROC)SDL_GL_GetProcAddress("glLoadTransposeMatrixdARB");
  glMultTransposeMatrixfARB = (PFNGLMULTTRANSPOSEMATRIXFARBPROC)SDL_GL_GetProcAddress("glMultTransposeMatrixfARB");
  glMultTransposeMatrixdARB = (PFNGLMULTTRANSPOSEMATRIXDARBPROC)SDL_GL_GetProcAddress("glMultTransposeMatrixdARB");
#endif
#ifdef SAGE_GL_ARB_multisample
  glSampleCoverageARB = (PFNGLSAMPLECOVERAGEARBPROC)SDL_GL_GetProcAddress("glSampleCoverageARB");
  glSamplePassARB = (PFNGLSAMPLEPASSARBPROC)SDL_GL_GetProcAddress("glSamplePassARB");
#endif
#ifdef SAGE_GL_ARB_texture_env_add
#endif
#ifdef SAGE_GL_ARB_texture_cube_map
#endif
#ifdef SAGE_GL_ARB_texture_compression
  glCompressedTexImage3DARB = (PFNGLCOMPRESSEDTEXIMAGE3DARBPROC)SDL_GL_GetProcAddress("glCompressedTexImage3DARB");
  glCompressedTexImage2DARB = (PFNGLCOMPRESSEDTEXIMAGE2DARBPROC)SDL_GL_GetProcAddress("glCompressedTexImage2DARB");
  glCompressedTexImage1DARB = (PFNGLCOMPRESSEDTEXIMAGE1DARBPROC)SDL_GL_GetProcAddress("glCompressedTexImage1DARB");
  glCompressedTexSubImage3DARB = (PFNGLCOMPRESSEDTEXSUBIMAGE3DARBPROC)SDL_GL_GetProcAddress("glCompressedTexSubImage3DARB");
  glCompressedTexSubImage2DARB = (PFNGLCOMPRESSEDTEXSUBIMAGE2DARBPROC)SDL_GL_GetProcAddress("glCompressedTexSubImage2DARB");
  glCompressedTexSubImage1DARB = (PFNGLCOMPRESSEDTEXSUBIMAGE1DARBPROC)SDL_GL_GetProcAddress("glCompressedTexSubImage1DARB");
  glGetCompressedTexImageARB = (PFNGLGETCOMPRESSEDTEXIMAGEARBPROC)SDL_GL_GetProcAddress("glGetCompressedTexImageARB");
#endif
#ifdef SAGE_GL_EXT_abgr
#endif
#ifdef SAGE_GL_EXT_blend_color
  glBlendColorEXT = (PFNGLBLENDCOLOREXTPROC)SDL_GL_GetProcAddress("glBlendColorEXT");
#endif
#ifdef SAGE_GL_EXT_polygon_offset
  glPolygonOffsetEXT = (PFNGLPOLYGONOFFSETEXTPROC)SDL_GL_GetProcAddress("glPolygonOffsetEXT");
#endif
#ifdef SAGE_GL_EXT_texture
#endif
#ifdef SAGE_GL_EXT_texture3D
  glTexImage3DEXT = (PFNGLTEXIMAGE3DEXTPROC)SDL_GL_GetProcAddress("glTexImage3DEXT");
  glTexSubImage3DEXT = (PFNGLTEXSUBIMAGE3DEXTPROC)SDL_GL_GetProcAddress("glTexSubImage3DEXT");
#endif
#ifdef SAGE_GL_SGIS_texture_filter4
  glGetTexFilterFuncSGIS = (PFNGLGETTEXFILTERFUNCSGISPROC)SDL_GL_GetProcAddress("glGetTexFilterFuncSGIS");
  glTexFilterFuncSGIS = (PFNGLTEXFILTERFUNCSGISPROC)SDL_GL_GetProcAddress("glTexFilterFuncSGIS");
#endif
#ifdef SAGE_GL_EXT_subtexture
  glTexSubImage1DEXT = (PFNGLTEXSUBIMAGE1DEXTPROC)SDL_GL_GetProcAddress("glTexSubImage1DEXT");
  glTexSubImage2DEXT = (PFNGLTEXSUBIMAGE2DEXTPROC)SDL_GL_GetProcAddress("glTexSubImage2DEXT");
#endif
#ifdef SAGE_GL_EXT_copy_texture
  glCopyTexImage1DEXT = (PFNGLCOPYTEXIMAGE1DEXTPROC)SDL_GL_GetProcAddress("glCopyTexImage1DEXT");
  glCopyTexImage2DEXT = (PFNGLCOPYTEXIMAGE2DEXTPROC)SDL_GL_GetProcAddress("glCopyTexImage2DEXT");
  glCopyTexSubImage1DEXT = (PFNGLCOPYTEXSUBIMAGE1DEXTPROC)SDL_GL_GetProcAddress("glCopyTexSubImage1DEXT");
  glCopyTexSubImage2DEXT = (PFNGLCOPYTEXSUBIMAGE2DEXTPROC)SDL_GL_GetProcAddress("glCopyTexSubImage2DEXT");
  glCopyTexSubImage3DEXT = (PFNGLCOPYTEXSUBIMAGE3DEXTPROC)SDL_GL_GetProcAddress("glCopyTexSubImage3DEXT");
#endif
#ifdef SAGE_GL_EXT_histogram
  glGetHistogramEXT = (PFNGLGETHISTOGRAMEXTPROC)SDL_GL_GetProcAddress("glGetHistogramEXT");
  glGetHistogramParameterfvEXT = (PFNGLGETHISTOGRAMPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glGetHistogramParameterfvEXT");
  glGetHistogramParameterivEXT = (PFNGLGETHISTOGRAMPARAMETERIVEXTPROC)SDL_GL_GetProcAddress("glGetHistogramParameterivEXT");
  glGetMinmaxEXT = (PFNGLGETMINMAXEXTPROC)SDL_GL_GetProcAddress("glGetMinmaxEXT");
  glGetMinmaxParameterfvEXT = (PFNGLGETMINMAXPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glGetMinmaxParameterfvEXT");
  glGetMinmaxParameterivEXT = (PFNGLGETMINMAXPARAMETERIVEXTPROC)SDL_GL_GetProcAddress("glGetMinmaxParameterivEXT");
  glHistogramEXT = (PFNGLHISTOGRAMEXTPROC)SDL_GL_GetProcAddress("glHistogramEXT");
  glMinmaxEXT = (PFNGLMINMAXEXTPROC)SDL_GL_GetProcAddress("glMinmaxEXT");
  glResetHistogramEXT = (PFNGLRESETHISTOGRAMEXTPROC)SDL_GL_GetProcAddress("glResetHistogramEXT");
  glResetMinmaxEXT = (PFNGLRESETMINMAXEXTPROC)SDL_GL_GetProcAddress("glResetMinmaxEXT");
#endif
#ifdef SAGE_GL_EXT_convolution
  glConvolutionFilter1DEXT = (PFNGLCONVOLUTIONFILTER1DEXTPROC)SDL_GL_GetProcAddress("glConvolutionFilter1DEXT");
  glConvolutionFilter2DEXT = (PFNGLCONVOLUTIONFILTER2DEXTPROC)SDL_GL_GetProcAddress("glConvolutionFilter2DEXT");
  glConvolutionParameterfEXT = (PFNGLCONVOLUTIONPARAMETERFEXTPROC)SDL_GL_GetProcAddress("glConvolutionParameterfEXT");
  glConvolutionParameterfvEXT = (PFNGLCONVOLUTIONPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glConvolutionParameterfvEXT");
  glConvolutionParameteriEXT = (PFNGLCONVOLUTIONPARAMETERIEXTPROC)SDL_GL_GetProcAddress("glConvolutionParameteriEXT");
  glConvolutionParameterivEXT = (PFNGLCONVOLUTIONPARAMETERIVEXTPROC)SDL_GL_GetProcAddress("glConvolutionParameterivEXT");
  glCopyConvolutionFilter1DEXT = (PFNGLCOPYCONVOLUTIONFILTER1DEXTPROC)SDL_GL_GetProcAddress("glCopyConvolutionFilter1DEXT");
  glCopyConvolutionFilter2DEXT = (PFNGLCOPYCONVOLUTIONFILTER2DEXTPROC)SDL_GL_GetProcAddress("glCopyConvolutionFilter2DEXT");
  glGetConvolutionFilterEXT = (PFNGLGETCONVOLUTIONFILTEREXTPROC)SDL_GL_GetProcAddress("glGetConvolutionFilterEXT");
  glGetConvolutionParameterfvEXT = (PFNGLGETCONVOLUTIONPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glGetConvolutionParameterfvEXT");
  glGetConvolutionParameterivEXT = (PFNGLGETCONVOLUTIONPARAMETERIVEXTPROC)SDL_GL_GetProcAddress("glGetConvolutionParameterivEXT");
  glGetSeparableFilterEXT = (PFNGLGETSEPARABLEFILTEREXTPROC)SDL_GL_GetProcAddress("glGetSeparableFilterEXT");
  glSeparableFilter2DEXT = (PFNGLSEPARABLEFILTER2DEXTPROC)SDL_GL_GetProcAddress("glSeparableFilter2DEXT");
#endif
#ifdef SAGE_GL_EXT_color_matrix
#endif
#ifdef SAGE_GL_SGI_color_table
  glColorTableSGI = (PFNGLCOLORTABLESGIPROC)SDL_GL_GetProcAddress("glColorTableSGI");
  glColorTableParameterfvSGI = (PFNGLCOLORTABLEPARAMETERFVSGIPROC)SDL_GL_GetProcAddress("glColorTableParameterfvSGI");
  glColorTableParameterivSGI = (PFNGLCOLORTABLEPARAMETERIVSGIPROC)SDL_GL_GetProcAddress("glColorTableParameterivSGI");
  glCopyColorTableSGI = (PFNGLCOPYCOLORTABLESGIPROC)SDL_GL_GetProcAddress("glCopyColorTableSGI");
  glGetColorTableSGI = (PFNGLGETCOLORTABLESGIPROC)SDL_GL_GetProcAddress("glGetColorTableSGI");
  glGetColorTableParameterfvSGI = (PFNGLGETCOLORTABLEPARAMETERFVSGIPROC)SDL_GL_GetProcAddress("glGetColorTableParameterfvSGI");
  glGetColorTableParameterivSGI = (PFNGLGETCOLORTABLEPARAMETERIVSGIPROC)SDL_GL_GetProcAddress("glGetColorTableParameterivSGI");
#endif
#ifdef SAGE_GL_SGIX_pixel_texture
  glPixelTexGenSGIX = (PFNGLPIXELTEXGENSGIXPROC)SDL_GL_GetProcAddress("glPixelTexGenSGIX");
#endif
#ifdef SAGE_GL_SGIS_pixel_texture
  glPixelTexGenParameteriSGIS = (PFNGLPIXELTEXGENPARAMETERISGISPROC)SDL_GL_GetProcAddress("glPixelTexGenParameteriSGIS");
  glPixelTexGenParameterivSGIS = (PFNGLPIXELTEXGENPARAMETERIVSGISPROC)SDL_GL_GetProcAddress("glPixelTexGenParameterivSGIS");
  glPixelTexGenParameterfSGIS = (PFNGLPIXELTEXGENPARAMETERFSGISPROC)SDL_GL_GetProcAddress("glPixelTexGenParameterfSGIS");
  glPixelTexGenParameterfvSGIS = (PFNGLPIXELTEXGENPARAMETERFVSGISPROC)SDL_GL_GetProcAddress("glPixelTexGenParameterfvSGIS");
  glGetPixelTexGenParameterivSGIS = (PFNGLGETPIXELTEXGENPARAMETERIVSGISPROC)SDL_GL_GetProcAddress("glGetPixelTexGenParameterivSGIS");
  glGetPixelTexGenParameterfvSGIS = (PFNGLGETPIXELTEXGENPARAMETERFVSGISPROC)SDL_GL_GetProcAddress("glGetPixelTexGenParameterfvSGIS");
#endif
#ifdef SAGE_GL_SGIS_texture4D
  glTexImage4DSGIS = (PFNGLTEXIMAGE4DSGISPROC)SDL_GL_GetProcAddress("glTexImage4DSGIS");
  glTexSubImage4DSGIS = (PFNGLTEXSUBIMAGE4DSGISPROC)SDL_GL_GetProcAddress("glTexSubImage4DSGIS");
#endif
#ifdef SAGE_GL_SGI_texture_color_table
#endif
#ifdef SAGE_GL_EXT_cmyka
#endif
#ifdef SAGE_GL_EXT_texture_object
  glAreTexturesResidentEXT = (PFNGLARETEXTURESRESIDENTEXTPROC)SDL_GL_GetProcAddress("glAreTexturesResidentEXT");
  glBindTextureEXT = (PFNGLBINDTEXTUREEXTPROC)SDL_GL_GetProcAddress("glBindTextureEXT");
  glDeleteTexturesEXT = (PFNGLDELETETEXTURESEXTPROC)SDL_GL_GetProcAddress("glDeleteTexturesEXT");
  glGenTexturesEXT = (PFNGLGENTEXTURESEXTPROC)SDL_GL_GetProcAddress("glGenTexturesEXT");
  glIsTextureEXT = (PFNGLISTEXTUREEXTPROC)SDL_GL_GetProcAddress("glIsTextureEXT");
  glPrioritizeTexturesEXT = (PFNGLPRIORITIZETEXTURESEXTPROC)SDL_GL_GetProcAddress("glPrioritizeTexturesEXT");
#endif
#ifdef SAGE_GL_SGIS_detail_texture
  glDetailTexFuncSGIS = (PFNGLDETAILTEXFUNCSGISPROC)SDL_GL_GetProcAddress("glDetailTexFuncSGIS");
  glGetDetailTexFuncSGIS = (PFNGLGETDETAILTEXFUNCSGISPROC)SDL_GL_GetProcAddress("glGetDetailTexFuncSGIS");
#endif
#ifdef SAGE_GL_SGIS_sharpen_texture
  glSharpenTexFuncSGIS = (PFNGLSHARPENTEXFUNCSGISPROC)SDL_GL_GetProcAddress("glSharpenTexFuncSGIS");
  glGetSharpenTexFuncSGIS = (PFNGLGETSHARPENTEXFUNCSGISPROC)SDL_GL_GetProcAddress("glGetSharpenTexFuncSGIS");
#endif
#ifdef SAGE_GL_EXT_packed_pixels
#endif
#ifdef SAGE_GL_SGIS_texture_lod
#endif
#ifdef SAGE_GL_SGIS_multisample
  glSampleMaskSGIS = (PFNGLSAMPLEMASKSGISPROC)SDL_GL_GetProcAddress("glSampleMaskSGIS");
  glSamplePatternSGIS = (PFNGLSAMPLEPATTERNSGISPROC)SDL_GL_GetProcAddress("glSamplePatternSGIS");
#endif
#ifdef SAGE_GL_EXT_rescale_normal
#endif
#ifdef SAGE_GL_EXT_vertex_array
  glArrayElementEXT = (PFNGLARRAYELEMENTEXTPROC)SDL_GL_GetProcAddress("glArrayElementEXT");
  glColorPointerEXT = (PFNGLCOLORPOINTEREXTPROC)SDL_GL_GetProcAddress("glColorPointerEXT");
  glDrawArraysEXT = (PFNGLDRAWARRAYSEXTPROC)SDL_GL_GetProcAddress("glDrawArraysEXT");
  glEdgeFlagPointerEXT = (PFNGLEDGEFLAGPOINTEREXTPROC)SDL_GL_GetProcAddress("glEdgeFlagPointerEXT");
  glGetPointervEXT = (PFNGLGETPOINTERVEXTPROC)SDL_GL_GetProcAddress("glGetPointervEXT");
  glIndexPointerEXT = (PFNGLINDEXPOINTEREXTPROC)SDL_GL_GetProcAddress("glIndexPointerEXT");
  glNormalPointerEXT = (PFNGLNORMALPOINTEREXTPROC)SDL_GL_GetProcAddress("glNormalPointerEXT");
  glTexCoordPointerEXT = (PFNGLTEXCOORDPOINTEREXTPROC)SDL_GL_GetProcAddress("glTexCoordPointerEXT");
  glVertexPointerEXT = (PFNGLVERTEXPOINTEREXTPROC)SDL_GL_GetProcAddress("glVertexPointerEXT");
#endif
#ifdef SAGE_GL_EXT_misc_attribute
#endif
#ifdef SAGE_GL_SGIS_generate_mipmap
#endif
#ifdef SAGE_GL_SGIX_clipmap
#endif
#ifdef SAGE_GL_SGIX_shadow
#endif
#ifdef SAGE_GL_SGIS_texture_edge_clamp
#endif
#ifdef SAGE_GL_SGIS_texture_border_clamp
#endif
#ifdef SAGE_GL_EXT_blend_minmax
  glBlendEquationEXT = (PFNGLBLENDEQUATIONEXTPROC)SDL_GL_GetProcAddress("glBlendEquationEXT");
#endif
#ifdef SAGE_GL_EXT_blend_subtract
#endif
#ifdef SAGE_GL_EXT_blend_logic_op
#endif
#ifdef SAGE_GL_SGIX_interlace
#endif
#ifdef SAGE_GL_SGIX_pixel_tiles
#endif
#ifdef SAGE_GL_SGIX_texture_select
#endif
#ifdef SAGE_GL_SGIX_sprite
  glSpriteParameterfSGIX = (PFNGLSPRITEPARAMETERFSGIXPROC)SDL_GL_GetProcAddress("glSpriteParameterfSGIX");
  glSpriteParameterfvSGIX = (PFNGLSPRITEPARAMETERFVSGIXPROC)SDL_GL_GetProcAddress("glSpriteParameterfvSGIX");
  glSpriteParameteriSGIX = (PFNGLSPRITEPARAMETERISGIXPROC)SDL_GL_GetProcAddress("glSpriteParameteriSGIX");
  glSpriteParameterivSGIX = (PFNGLSPRITEPARAMETERIVSGIXPROC)SDL_GL_GetProcAddress("glSpriteParameterivSGIX");
#endif
#ifdef SAGE_GL_SGIX_texture_multi_buffer
#endif
#ifdef SAGE_GL_EXT_point_parameters
  glPointParameterfEXT = (PFNGLPOINTPARAMETERFEXTPROC)SDL_GL_GetProcAddress("glPointParameterfEXT");
  glPointParameterfvEXT = (PFNGLPOINTPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glPointParameterfvEXT");
  glPointParameterfSGIS = (PFNGLPOINTPARAMETERFSGISPROC)SDL_GL_GetProcAddress("glPointParameterfSGIS");
  glPointParameterfvSGIS = (PFNGLPOINTPARAMETERFVSGISPROC)SDL_GL_GetProcAddress("glPointParameterfvSGIS");
#endif
#ifdef SAGE_GL_SGIX_instruments
  glGetInstrumentsSGIX = (PFNGLGETINSTRUMENTSSGIXPROC)SDL_GL_GetProcAddress("glGetInstrumentsSGIX");
  glInstrumentsBufferSGIX = (PFNGLINSTRUMENTSBUFFERSGIXPROC)SDL_GL_GetProcAddress("glInstrumentsBufferSGIX");
  glPollInstrumentsSGIX = (PFNGLPOLLINSTRUMENTSSGIXPROC)SDL_GL_GetProcAddress("glPollInstrumentsSGIX");
  glReadInstrumentsSGIX = (PFNGLREADINSTRUMENTSSGIXPROC)SDL_GL_GetProcAddress("glReadInstrumentsSGIX");
  glStartInstrumentsSGIX = (PFNGLSTARTINSTRUMENTSSGIXPROC)SDL_GL_GetProcAddress("glStartInstrumentsSGIX");
  glStopInstrumentsSGIX = (PFNGLSTOPINSTRUMENTSSGIXPROC)SDL_GL_GetProcAddress("glStopInstrumentsSGIX");
#endif
#ifdef SAGE_GL_SGIX_texture_scale_bias
#endif
#ifdef SAGE_GL_SGIX_framezoom
  glFrameZoomSGIX = (PFNGLFRAMEZOOMSGIXPROC)SDL_GL_GetProcAddress("glFrameZoomSGIX");
#endif
#ifdef SAGE_GL_SGIX_tag_sample_buffer
  glTagSampleBufferSGIX = (PFNGLTAGSAMPLEBUFFERSGIXPROC)SDL_GL_GetProcAddress("glTagSampleBufferSGIX");
#endif
#ifdef SAGE_GL_SGIX_polynomial_ffd
  glDeformationMap3dSGIX = (PFNGLDEFORMATIONMAP3DSGIXPROC)SDL_GL_GetProcAddress("glDeformationMap3dSGIX");
  glDeformationMap3fSGIX = (PFNGLDEFORMATIONMAP3FSGIXPROC)SDL_GL_GetProcAddress("glDeformationMap3fSGIX");
  glDeformSGIX = (PFNGLDEFORMSGIXPROC)SDL_GL_GetProcAddress("glDeformSGIX");
  glLoadIdentityDeformationMapSGIX = (PFNGLLOADIDENTITYDEFORMATIONMAPSGIXPROC)SDL_GL_GetProcAddress("glLoadIdentityDeformationMapSGIX");
#endif
#ifdef SAGE_GL_SGIX_reference_plane
  glReferencePlaneSGIX = (PFNGLREFERENCEPLANESGIXPROC)SDL_GL_GetProcAddress("glReferencePlaneSGIX");
#endif
#ifdef SAGE_GL_SGIX_flush_raster
  glFlushRasterSGIX = (PFNGLFLUSHRASTERSGIXPROC)SDL_GL_GetProcAddress("glFlushRasterSGIX");
#endif
#ifdef SAGE_GL_SGIX_depth_texture
#endif
#ifdef SAGE_GL_SGIS_fog_function
  glFogFuncSGIS = (PFNGLFOGFUNCSGISPROC)SDL_GL_GetProcAddress("glFogFuncSGIS");
  glGetFogFuncSGIS = (PFNGLGETFOGFUNCSGISPROC)SDL_GL_GetProcAddress("glGetFogFuncSGIS");
#endif
#ifdef SAGE_GL_SGIX_fog_offset
#endif
#ifdef SAGE_GL_HP_image_transform
  glImageTransformParameteriHP = (PFNGLIMAGETRANSFORMPARAMETERIHPPROC)SDL_GL_GetProcAddress("glImageTransformParameteriHP");
  glImageTransformParameterfHP = (PFNGLIMAGETRANSFORMPARAMETERFHPPROC)SDL_GL_GetProcAddress("glImageTransformParameterfHP");
  glImageTransformParameterivHP = (PFNGLIMAGETRANSFORMPARAMETERIVHPPROC)SDL_GL_GetProcAddress("glImageTransformParameterivHP");
  glImageTransformParameterfvHP = (PFNGLIMAGETRANSFORMPARAMETERFVHPPROC)SDL_GL_GetProcAddress("glImageTransformParameterfvHP");
  glGetImageTransformParameterivHP = (PFNGLGETIMAGETRANSFORMPARAMETERIVHPPROC)SDL_GL_GetProcAddress("glGetImageTransformParameterivHP");
  glGetImageTransformParameterfvHP = (PFNGLGETIMAGETRANSFORMPARAMETERFVHPPROC)SDL_GL_GetProcAddress("glGetImageTransformParameterfvHP");
#endif
#ifdef SAGE_GL_HP_convolution_border_modes
#endif
#ifdef SAGE_GL_SGIX_texture_add_env
#endif
#ifdef SAGE_GL_EXT_color_subtable
  glColorSubTableEXT = (PFNGLCOLORSUBTABLEEXTPROC)SDL_GL_GetProcAddress("glColorSubTableEXT");
  glCopyColorSubTableEXT = (PFNGLCOPYCOLORSUBTABLEEXTPROC)SDL_GL_GetProcAddress("glCopyColorSubTableEXT");
#endif
#ifdef SAGE_GL_PGI_vertex_hints
#endif
#ifdef SAGE_GL_PGI_misc_hints
  glHintPGI = (PFNGLHINTPGIPROC)SDL_GL_GetProcAddress("glHintPGI");
#endif
#ifdef SAGE_GL_EXT_paletted_texture
  glColorTableEXT = (PFNGLCOLORTABLEEXTPROC)SDL_GL_GetProcAddress("glColorTableEXT");
  glGetColorTableEXT = (PFNGLGETCOLORTABLEEXTPROC)SDL_GL_GetProcAddress("glGetColorTableEXT");
  glGetColorTableParameterivEXT = (PFNGLGETCOLORTABLEPARAMETERIVEXTPROC)SDL_GL_GetProcAddress("glGetColorTableParameterivEXT");
  glGetColorTableParameterfvEXT = (PFNGLGETCOLORTABLEPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glGetColorTableParameterfvEXT");
#endif
#ifdef SAGE_GL_EXT_clip_volume_hint
#endif
#ifdef SAGE_GL_SGIX_list_priority
  glGetListParameterfvSGIX = (PFNGLGETLISTPARAMETERFVSGIXPROC)SDL_GL_GetProcAddress("glGetListParameterfvSGIX");
  glGetListParameterivSGIX = (PFNGLGETLISTPARAMETERIVSGIXPROC)SDL_GL_GetProcAddress("glGetListParameterivSGIX");
  glListParameterfSGIX = (PFNGLLISTPARAMETERFSGIXPROC)SDL_GL_GetProcAddress("glListParameterfSGIX");
  glListParameterfvSGIX = (PFNGLLISTPARAMETERFVSGIXPROC)SDL_GL_GetProcAddress("glListParameterfvSGIX");
  glListParameteriSGIX = (PFNGLLISTPARAMETERISGIXPROC)SDL_GL_GetProcAddress("glListParameteriSGIX");
  glListParameterivSGIX = (PFNGLLISTPARAMETERIVSGIXPROC)SDL_GL_GetProcAddress("glListParameterivSGIX");
#endif
#ifdef SAGE_GL_SGIX_ir_instrument1
#endif
#ifdef SAGE_GL_SGIX_calligraphic_fragment
#endif
#ifdef SAGE_GL_SGIX_texture_lod_bias
#endif
#ifdef SAGE_GL_SGIX_shadow_ambient
#endif
#ifdef SAGE_GL_EXT_index_texture
#endif
#ifdef SAGE_GL_EXT_index_material
  glIndexMaterialEXT = (PFNGLINDEXMATERIALEXTPROC)SDL_GL_GetProcAddress("glIndexMaterialEXT");
#endif
#ifdef SAGE_GL_EXT_index_func
  glIndexFuncEXT = (PFNGLINDEXFUNCEXTPROC)SDL_GL_GetProcAddress("glIndexFuncEXT");
#endif
#ifdef SAGE_GL_EXT_index_array_formats
#endif
#ifdef SAGE_GL_EXT_compiled_vertex_array
  glLockArraysEXT = (PFNGLLOCKARRAYSEXTPROC)SDL_GL_GetProcAddress("glLockArraysEXT");
  glUnlockArraysEXT = (PFNGLUNLOCKARRAYSEXTPROC)SDL_GL_GetProcAddress("glUnlockArraysEXT");
#endif
#ifdef SAGE_GL_EXT_cull_vertex
  glCullParameterdvEXT = (PFNGLCULLPARAMETERDVEXTPROC)SDL_GL_GetProcAddress("glCullParameterdvEXT");
  glCullParameterfvEXT = (PFNGLCULLPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glCullParameterfvEXT");
#endif
#ifdef SAGE_GL_SGIX_ycrcb
#endif
#ifdef SAGE_GL_SGIX_fragment_lighting
  glFragmentColorMaterialSGIX = (PFNGLFRAGMENTCOLORMATERIALSGIXPROC)SDL_GL_GetProcAddress("glFragmentColorMaterialSGIX");
  glFragmentLightfSGIX = (PFNGLFRAGMENTLIGHTFSGIXPROC)SDL_GL_GetProcAddress("glFragmentLightfSGIX");
  glFragmentLightfvSGIX = (PFNGLFRAGMENTLIGHTFVSGIXPROC)SDL_GL_GetProcAddress("glFragmentLightfvSGIX");
  glFragmentLightiSGIX = (PFNGLFRAGMENTLIGHTISGIXPROC)SDL_GL_GetProcAddress("glFragmentLightiSGIX");
  glFragmentLightivSGIX = (PFNGLFRAGMENTLIGHTIVSGIXPROC)SDL_GL_GetProcAddress("glFragmentLightivSGIX");
  glFragmentLightModelfSGIX = (PFNGLFRAGMENTLIGHTMODELFSGIXPROC)SDL_GL_GetProcAddress("glFragmentLightModelfSGIX");
  glFragmentLightModelfvSGIX = (PFNGLFRAGMENTLIGHTMODELFVSGIXPROC)SDL_GL_GetProcAddress("glFragmentLightModelfvSGIX");
  glFragmentLightModeliSGIX = (PFNGLFRAGMENTLIGHTMODELISGIXPROC)SDL_GL_GetProcAddress("glFragmentLightModeliSGIX");
  glFragmentLightModelivSGIX = (PFNGLFRAGMENTLIGHTMODELIVSGIXPROC)SDL_GL_GetProcAddress("glFragmentLightModelivSGIX");
  glFragmentMaterialfSGIX = (PFNGLFRAGMENTMATERIALFSGIXPROC)SDL_GL_GetProcAddress("glFragmentMaterialfSGIX");
  glFragmentMaterialfvSGIX = (PFNGLFRAGMENTMATERIALFVSGIXPROC)SDL_GL_GetProcAddress("glFragmentMaterialfvSGIX");
  glFragmentMaterialiSGIX = (PFNGLFRAGMENTMATERIALISGIXPROC)SDL_GL_GetProcAddress("glFragmentMaterialiSGIX");
  glFragmentMaterialivSGIX = (PFNGLFRAGMENTMATERIALIVSGIXPROC)SDL_GL_GetProcAddress("glFragmentMaterialivSGIX");
  glGetFragmentLightfvSGIX = (PFNGLGETFRAGMENTLIGHTFVSGIXPROC)SDL_GL_GetProcAddress("glGetFragmentLightfvSGIX");
  glGetFragmentLightivSGIX = (PFNGLGETFRAGMENTLIGHTIVSGIXPROC)SDL_GL_GetProcAddress("glGetFragmentLightivSGIX");
  glGetFragmentMaterialfvSGIX = (PFNGLGETFRAGMENTMATERIALFVSGIXPROC)SDL_GL_GetProcAddress("glGetFragmentMaterialfvSGIX");
  glGetFragmentMaterialivSGIX = (PFNGLGETFRAGMENTMATERIALIVSGIXPROC)SDL_GL_GetProcAddress("glGetFragmentMaterialivSGIX");
  glLightEnviSGIX = (PFNGLLIGHTENVISGIXPROC)SDL_GL_GetProcAddress("glLightEnviSGIX");
#endif
#ifdef SAGE_GL_IBM_rasterpos_clip
#endif
#ifdef SAGE_GL_HP_texture_lighting
#endif
#ifdef SAGE_GL_EXT_draw_range_elements
  glDrawRangeElementsEXT = (PFNGLDRAWRANGEELEMENTSEXTPROC)SDL_GL_GetProcAddress("glDrawRangeElementsEXT");
#endif
#ifdef SAGE_GL_WIN_phong_shading
#endif
#ifdef SAGE_GL_WIN_specular_fog
#endif
#ifdef SAGE_GL_EXT_light_texture
  glApplyTextureEXT = (PFNGLAPPLYTEXTUREEXTPROC)SDL_GL_GetProcAddress("glApplyTextureEXT");
  glTextureLightEXT = (PFNGLTEXTURELIGHTEXTPROC)SDL_GL_GetProcAddress("glTextureLightEXT");
  glTextureMaterialEXT = (PFNGLTEXTUREMATERIALEXTPROC)SDL_GL_GetProcAddress("glTextureMaterialEXT");
#endif
#ifdef SAGE_GL_SGIX_blend_alpha_minmax
#endif
#ifdef SAGE_GL_EXT_bgra
#endif
#ifdef SAGE_GL_SGIX_async
  glAsyncMarkerSGIX = (PFNGLASYNCMARKERSGIXPROC)SDL_GL_GetProcAddress("glAsyncMarkerSGIX");
  glFinishAsyncSGIX = (PFNGLFINISHASYNCSGIXPROC)SDL_GL_GetProcAddress("glFinishAsyncSGIX");
  glPollAsyncSGIX = (PFNGLPOLLASYNCSGIXPROC)SDL_GL_GetProcAddress("glPollAsyncSGIX");
  glGenAsyncMarkersSGIX = (PFNGLGENASYNCMARKERSSGIXPROC)SDL_GL_GetProcAddress("glGenAsyncMarkersSGIX");
  glDeleteAsyncMarkersSGIX = (PFNGLDELETEASYNCMARKERSSGIXPROC)SDL_GL_GetProcAddress("glDeleteAsyncMarkersSGIX");
  glIsAsyncMarkerSGIX = (PFNGLISASYNCMARKERSGIXPROC)SDL_GL_GetProcAddress("glIsAsyncMarkerSGIX");
#endif
#ifdef SAGE_GL_SGIX_async_pixel
#endif
#ifdef SAGE_GL_SGIX_async_histogram
#endif
#ifdef SAGE_GL_INTEL_parallel_arrays
  glVertexPointervINTEL = (PFNGLVERTEXPOINTERVINTELPROC)SDL_GL_GetProcAddress("glVertexPointervINTEL");
  glNormalPointervINTEL = (PFNGLNORMALPOINTERVINTELPROC)SDL_GL_GetProcAddress("glNormalPointervINTEL");
  glColorPointervINTEL = (PFNGLCOLORPOINTERVINTELPROC)SDL_GL_GetProcAddress("glColorPointervINTEL");
  glTexCoordPointervINTEL = (PFNGLTEXCOORDPOINTERVINTELPROC)SDL_GL_GetProcAddress("glTexCoordPointervINTEL");
#endif
#ifdef SAGE_GL_HP_occlusion_test
#endif
#ifdef SAGE_GL_EXT_pixel_transform
  glPixelTransformParameteriEXT = (PFNGLPIXELTRANSFORMPARAMETERIEXTPROC)SDL_GL_GetProcAddress("glPixelTransformParameteriEXT");
  glPixelTransformParameterfEXT = (PFNGLPIXELTRANSFORMPARAMETERFEXTPROC)SDL_GL_GetProcAddress("glPixelTransformParameterfEXT");
  glPixelTransformParameterivEXT = (PFNGLPIXELTRANSFORMPARAMETERIVEXTPROC)SDL_GL_GetProcAddress("glPixelTransformParameterivEXT");
  glPixelTransformParameterfvEXT = (PFNGLPIXELTRANSFORMPARAMETERFVEXTPROC)SDL_GL_GetProcAddress("glPixelTransformParameterfvEXT");
#endif
#ifdef SAGE_GL_EXT_pixel_transform_color_table
#endif
#ifdef SAGE_GL_EXT_shared_texture_palette
#endif
#ifdef SAGE_GL_EXT_separate_specular_color
#endif
#ifdef SAGE_GL_EXT_secondary_color
  glSecondaryColor3bEXT = (PFNGLSECONDARYCOLOR3BEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3bEXT");
  glSecondaryColor3bvEXT = (PFNGLSECONDARYCOLOR3BVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3bvEXT");
  glSecondaryColor3dEXT = (PFNGLSECONDARYCOLOR3DEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3dEXT");
  glSecondaryColor3dvEXT = (PFNGLSECONDARYCOLOR3DVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3dvEXT");
  glSecondaryColor3fEXT = (PFNGLSECONDARYCOLOR3FEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3fEXT");
  glSecondaryColor3fvEXT = (PFNGLSECONDARYCOLOR3FVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3fvEXT");
  glSecondaryColor3iEXT = (PFNGLSECONDARYCOLOR3IEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3iEXT");
  glSecondaryColor3ivEXT = (PFNGLSECONDARYCOLOR3IVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3ivEXT");
  glSecondaryColor3sEXT = (PFNGLSECONDARYCOLOR3SEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3sEXT");
  glSecondaryColor3svEXT = (PFNGLSECONDARYCOLOR3SVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3svEXT");
  glSecondaryColor3ubEXT = (PFNGLSECONDARYCOLOR3UBEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3ubEXT");
  glSecondaryColor3ubvEXT = (PFNGLSECONDARYCOLOR3UBVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3ubvEXT");
  glSecondaryColor3uiEXT = (PFNGLSECONDARYCOLOR3UIEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3uiEXT");
  glSecondaryColor3uivEXT = (PFNGLSECONDARYCOLOR3UIVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3uivEXT");
  glSecondaryColor3usEXT = (PFNGLSECONDARYCOLOR3USEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3usEXT");
  glSecondaryColor3usvEXT = (PFNGLSECONDARYCOLOR3USVEXTPROC)SDL_GL_GetProcAddress("glSecondaryColor3usvEXT");
  glSecondaryColorPointerEXT = (PFNGLSECONDARYCOLORPOINTEREXTPROC)SDL_GL_GetProcAddress("glSecondaryColorPointerEXT");
#endif
#ifdef SAGE_GL_EXT_texture_perturb_normal
  glTextureNormalEXT = (PFNGLTEXTURENORMALEXTPROC)SDL_GL_GetProcAddress("glTextureNormalEXT");
#endif
#ifdef SAGE_GL_EXT_multi_draw_arrays
  glMultiDrawArraysEXT = (PFNGLMULTIDRAWARRAYSEXTPROC)SDL_GL_GetProcAddress("glMultiDrawArraysEXT");
  glMultiDrawElementsEXT = (PFNGLMULTIDRAWELEMENTSEXTPROC)SDL_GL_GetProcAddress("glMultiDrawElementsEXT");
#endif
#ifdef SAGE_GL_EXT_fog_coord
  glFogCoordfEXT = (PFNGLFOGCOORDFEXTPROC)SDL_GL_GetProcAddress("glFogCoordfEXT");
  glFogCoordfvEXT = (PFNGLFOGCOORDFVEXTPROC)SDL_GL_GetProcAddress("glFogCoordfvEXT");
  glFogCoorddEXT = (PFNGLFOGCOORDDEXTPROC)SDL_GL_GetProcAddress("glFogCoorddEXT");
  glFogCoorddvEXT = (PFNGLFOGCOORDDVEXTPROC)SDL_GL_GetProcAddress("glFogCoorddvEXT");
  glFogCoordPointerEXT = (PFNGLFOGCOORDPOINTEREXTPROC)SDL_GL_GetProcAddress("glFogCoordPointerEXT");
#endif
#ifdef SAGE_GL_REND_screen_coordinates
#endif
#ifdef SAGE_GL_EXT_coordinate_frame
  glTangent3bEXT = (PFNGLTANGENT3BEXTPROC)SDL_GL_GetProcAddress("glTangent3bEXT");
  glTangent3bvEXT = (PFNGLTANGENT3BVEXTPROC)SDL_GL_GetProcAddress("glTangent3bvEXT");
  glTangent3dEXT = (PFNGLTANGENT3DEXTPROC)SDL_GL_GetProcAddress("glTangent3dEXT");
  glTangent3dvEXT = (PFNGLTANGENT3DVEXTPROC)SDL_GL_GetProcAddress("glTangent3dvEXT");
  glTangent3fEXT = (PFNGLTANGENT3FEXTPROC)SDL_GL_GetProcAddress("glTangent3fEXT");
  glTangent3fvEXT = (PFNGLTANGENT3FVEXTPROC)SDL_GL_GetProcAddress("glTangent3fvEXT");
  glTangent3iEXT = (PFNGLTANGENT3IEXTPROC)SDL_GL_GetProcAddress("glTangent3iEXT");
  glTangent3ivEXT = (PFNGLTANGENT3IVEXTPROC)SDL_GL_GetProcAddress("glTangent3ivEXT");
  glTangent3sEXT = (PFNGLTANGENT3SEXTPROC)SDL_GL_GetProcAddress("glTangent3sEXT");
  glTangent3svEXT = (PFNGLTANGENT3SVEXTPROC)SDL_GL_GetProcAddress("glTangent3svEXT");
  glBinormal3bEXT = (PFNGLBINORMAL3BEXTPROC)SDL_GL_GetProcAddress("glBinormal3bEXT");
  glBinormal3bvEXT = (PFNGLBINORMAL3BVEXTPROC)SDL_GL_GetProcAddress("glBinormal3bvEXT");
  glBinormal3dEXT = (PFNGLBINORMAL3DEXTPROC)SDL_GL_GetProcAddress("glBinormal3dEXT");
  glBinormal3dvEXT = (PFNGLBINORMAL3DVEXTPROC)SDL_GL_GetProcAddress("glBinormal3dvEXT");
  glBinormal3fEXT = (PFNGLBINORMAL3FEXTPROC)SDL_GL_GetProcAddress("glBinormal3fEXT");
  glBinormal3fvEXT = (PFNGLBINORMAL3FVEXTPROC)SDL_GL_GetProcAddress("glBinormal3fvEXT");
  glBinormal3iEXT = (PFNGLBINORMAL3IEXTPROC)SDL_GL_GetProcAddress("glBinormal3iEXT");
  glBinormal3ivEXT = (PFNGLBINORMAL3IVEXTPROC)SDL_GL_GetProcAddress("glBinormal3ivEXT");
  glBinormal3sEXT = (PFNGLBINORMAL3SEXTPROC)SDL_GL_GetProcAddress("glBinormal3sEXT");
  glBinormal3svEXT = (PFNGLBINORMAL3SVEXTPROC)SDL_GL_GetProcAddress("glBinormal3svEXT");
  glTangentPointerEXT = (PFNGLTANGENTPOINTEREXTPROC)SDL_GL_GetProcAddress("glTangentPointerEXT");
  glBinormalPointerEXT = (PFNGLBINORMALPOINTEREXTPROC)SDL_GL_GetProcAddress("glBinormalPointerEXT");
#endif
#ifdef SAGE_GL_EXT_texture_env_combine
#endif
#ifdef SAGE_GL_APPLE_specular_vector
#endif
#ifdef SAGE_GL_APPLE_transform_hint
#endif
#ifdef SAGE_GL_SGIX_fog_scale
#endif
#ifdef SAGE_GL_SUNX_constant_data
  glFinishTextureSUNX = (PFNGLFINISHTEXTURESUNXPROC)SDL_GL_GetProcAddress("glFinishTextureSUNX");
#endif
#ifdef SAGE_GL_SUN_global_alpha
  glGlobalAlphaFactorbSUN = (PFNGLGLOBALALPHAFACTORBSUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactorbSUN");
  glGlobalAlphaFactorsSUN = (PFNGLGLOBALALPHAFACTORSSUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactorsSUN");
  glGlobalAlphaFactoriSUN = (PFNGLGLOBALALPHAFACTORISUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactoriSUN");
  glGlobalAlphaFactorfSUN = (PFNGLGLOBALALPHAFACTORFSUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactorfSUN");
  glGlobalAlphaFactordSUN = (PFNGLGLOBALALPHAFACTORDSUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactordSUN");
  glGlobalAlphaFactorubSUN = (PFNGLGLOBALALPHAFACTORUBSUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactorubSUN");
  glGlobalAlphaFactorusSUN = (PFNGLGLOBALALPHAFACTORUSSUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactorusSUN");
  glGlobalAlphaFactoruiSUN = (PFNGLGLOBALALPHAFACTORUISUNPROC)SDL_GL_GetProcAddress("glGlobalAlphaFactoruiSUN");
#endif
#ifdef SAGE_GL_SUN_triangle_list
  glReplacementCodeuiSUN = (PFNGLREPLACEMENTCODEUISUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiSUN");
  glReplacementCodeusSUN = (PFNGLREPLACEMENTCODEUSSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeusSUN");
  glReplacementCodeubSUN = (PFNGLREPLACEMENTCODEUBSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeubSUN");
  glReplacementCodeuivSUN = (PFNGLREPLACEMENTCODEUIVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuivSUN");
  glReplacementCodeusvSUN = (PFNGLREPLACEMENTCODEUSVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeusvSUN");
  glReplacementCodeubvSUN = (PFNGLREPLACEMENTCODEUBVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeubvSUN");
  glReplacementCodePointerSUN = (PFNGLREPLACEMENTCODEPOINTERSUNPROC)SDL_GL_GetProcAddress("glReplacementCodePointerSUN");
#endif
#ifdef SAGE_GL_SUN_vertex
  glColor4ubVertex2fSUN = (PFNGLCOLOR4UBVERTEX2FSUNPROC)SDL_GL_GetProcAddress("glColor4ubVertex2fSUN");
  glColor4ubVertex2fvSUN = (PFNGLCOLOR4UBVERTEX2FVSUNPROC)SDL_GL_GetProcAddress("glColor4ubVertex2fvSUN");
  glColor4ubVertex3fSUN = (PFNGLCOLOR4UBVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glColor4ubVertex3fSUN");
  glColor4ubVertex3fvSUN = (PFNGLCOLOR4UBVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glColor4ubVertex3fvSUN");
  glColor3fVertex3fSUN = (PFNGLCOLOR3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glColor3fVertex3fSUN");
  glColor3fVertex3fvSUN = (PFNGLCOLOR3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glColor3fVertex3fvSUN");
  glNormal3fVertex3fSUN = (PFNGLNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glNormal3fVertex3fSUN");
  glNormal3fVertex3fvSUN = (PFNGLNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glNormal3fVertex3fvSUN");
  glColor4fNormal3fVertex3fSUN = (PFNGLCOLOR4FNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glColor4fNormal3fVertex3fSUN");
  glColor4fNormal3fVertex3fvSUN = (PFNGLCOLOR4FNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glColor4fNormal3fVertex3fvSUN");
  glTexCoord2fVertex3fSUN = (PFNGLTEXCOORD2FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fVertex3fSUN");
  glTexCoord2fVertex3fvSUN = (PFNGLTEXCOORD2FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fVertex3fvSUN");
  glTexCoord4fVertex4fSUN = (PFNGLTEXCOORD4FVERTEX4FSUNPROC)SDL_GL_GetProcAddress("glTexCoord4fVertex4fSUN");
  glTexCoord4fVertex4fvSUN = (PFNGLTEXCOORD4FVERTEX4FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord4fVertex4fvSUN");
  glTexCoord2fColor4ubVertex3fSUN = (PFNGLTEXCOORD2FCOLOR4UBVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fColor4ubVertex3fSUN");
  glTexCoord2fColor4ubVertex3fvSUN = (PFNGLTEXCOORD2FCOLOR4UBVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fColor4ubVertex3fvSUN");
  glTexCoord2fColor3fVertex3fSUN = (PFNGLTEXCOORD2FCOLOR3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fColor3fVertex3fSUN");
  glTexCoord2fColor3fVertex3fvSUN = (PFNGLTEXCOORD2FCOLOR3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fColor3fVertex3fvSUN");
  glTexCoord2fNormal3fVertex3fSUN = (PFNGLTEXCOORD2FNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fNormal3fVertex3fSUN");
  glTexCoord2fNormal3fVertex3fvSUN = (PFNGLTEXCOORD2FNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fNormal3fVertex3fvSUN");
  glTexCoord2fColor4fNormal3fVertex3fSUN = (PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fColor4fNormal3fVertex3fSUN");
  glTexCoord2fColor4fNormal3fVertex3fvSUN = (PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord2fColor4fNormal3fVertex3fvSUN");
  glTexCoord4fColor4fNormal3fVertex4fSUN = (PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FSUNPROC)SDL_GL_GetProcAddress("glTexCoord4fColor4fNormal3fVertex4fSUN");
  glTexCoord4fColor4fNormal3fVertex4fvSUN = (PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FVSUNPROC)SDL_GL_GetProcAddress("glTexCoord4fColor4fNormal3fVertex4fvSUN");
  glReplacementCodeuiVertex3fSUN = (PFNGLREPLACEMENTCODEUIVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiVertex3fSUN");
  glReplacementCodeuiVertex3fvSUN = (PFNGLREPLACEMENTCODEUIVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiVertex3fvSUN");
  glReplacementCodeuiColor4ubVertex3fSUN = (PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiColor4ubVertex3fSUN");
  glReplacementCodeuiColor4ubVertex3fvSUN = (PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiColor4ubVertex3fvSUN");
  glReplacementCodeuiColor3fVertex3fSUN = (PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiColor3fVertex3fSUN");
  glReplacementCodeuiColor3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiColor3fVertex3fvSUN");
  glReplacementCodeuiNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiNormal3fVertex3fSUN");
  glReplacementCodeuiNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiNormal3fVertex3fvSUN");
  glReplacementCodeuiColor4fNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiColor4fNormal3fVertex3fSUN");
  glReplacementCodeuiColor4fNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiColor4fNormal3fVertex3fvSUN");
  glReplacementCodeuiTexCoord2fVertex3fSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiTexCoord2fVertex3fSUN");
  glReplacementCodeuiTexCoord2fVertex3fvSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiTexCoord2fVertex3fvSUN");
  glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN");
  glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN");
  glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN");
  glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC)SDL_GL_GetProcAddress("glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN");
#endif
#ifdef SAGE_GL_EXT_blend_func_separate
  glBlendFuncSeparateEXT = (PFNGLBLENDFUNCSEPARATEEXTPROC)SDL_GL_GetProcAddress("glBlendFuncSeparateEXT");
#endif
#ifdef SAGE_GL_INGR_color_clamp
#endif
#ifdef SAGE_GL_INGR_interlace_read
#endif
#ifdef SAGE_GL_EXT_stencil_wrap
#endif
#ifdef SAGE_GL_EXT_422_pixels
#endif
#ifdef SAGE_GL_NV_texgen_reflection
#endif
#ifdef SAGE_GL_SUN_convolution_border_modes
#endif
#ifdef SAGE_GL_EXT_texture_env_add
#endif
#ifdef SAGE_GL_EXT_texture_lod_bias
#endif
#ifdef SAGE_GL_EXT_texture_filter_anisotropic
#endif
#ifdef SAGE_GL_EXT_vertex_weighting
  glVertexWeightfEXT = (PFNGLVERTEXWEIGHTFEXTPROC)SDL_GL_GetProcAddress("glVertexWeightfEXT");
  glVertexWeightfvEXT = (PFNGLVERTEXWEIGHTFVEXTPROC)SDL_GL_GetProcAddress("glVertexWeightfvEXT");
  glVertexWeightPointerEXT = (PFNGLVERTEXWEIGHTPOINTEREXTPROC)SDL_GL_GetProcAddress("glVertexWeightPointerEXT");
#endif
#ifdef SAGE_GL_NV_light_max_exponent
#endif
#ifdef SAGE_GL_NV_vertex_array_range
  glFlushVertexArrayRangeNV = (PFNGLFLUSHVERTEXARRAYRANGENVPROC)SDL_GL_GetProcAddress("glFlushVertexArrayRangeNV");
  glVertexArrayRangeNV = (PFNGLVERTEXARRAYRANGENVPROC)SDL_GL_GetProcAddress("glVertexArrayRangeNV");
#endif
#ifdef SAGE_GL_NV_register_combiners
  glCombinerParameterfvNV = (PFNGLCOMBINERPARAMETERFVNVPROC)SDL_GL_GetProcAddress("glCombinerParameterfvNV");
  glCombinerParameterfNV = (PFNGLCOMBINERPARAMETERFNVPROC)SDL_GL_GetProcAddress("glCombinerParameterfNV");
  glCombinerParameterivNV = (PFNGLCOMBINERPARAMETERIVNVPROC)SDL_GL_GetProcAddress("glCombinerParameterivNV");
  glCombinerParameteriNV = (PFNGLCOMBINERPARAMETERINVPROC)SDL_GL_GetProcAddress("glCombinerParameteriNV");
  glCombinerInputNV = (PFNGLCOMBINERINPUTNVPROC)SDL_GL_GetProcAddress("glCombinerInputNV");
  glCombinerOutputNV = (PFNGLCOMBINEROUTPUTNVPROC)SDL_GL_GetProcAddress("glCombinerOutputNV");
  glFinalCombinerInputNV = (PFNGLFINALCOMBINERINPUTNVPROC)SDL_GL_GetProcAddress("glFinalCombinerInputNV");
  glGetCombinerInputParameterfvNV = (PFNGLGETCOMBINERINPUTPARAMETERFVNVPROC)SDL_GL_GetProcAddress("glGetCombinerInputParameterfvNV");
  glGetCombinerInputParameterivNV = (PFNGLGETCOMBINERINPUTPARAMETERIVNVPROC)SDL_GL_GetProcAddress("glGetCombinerInputParameterivNV");
  glGetCombinerOutputParameterfvNV = (PFNGLGETCOMBINEROUTPUTPARAMETERFVNVPROC)SDL_GL_GetProcAddress("glGetCombinerOutputParameterfvNV");
  glGetCombinerOutputParameterivNV = (PFNGLGETCOMBINEROUTPUTPARAMETERIVNVPROC)SDL_GL_GetProcAddress("glGetCombinerOutputParameterivNV");
  glGetFinalCombinerInputParameterfvNV = (PFNGLGETFINALCOMBINERINPUTPARAMETERFVNVPROC)SDL_GL_GetProcAddress("glGetFinalCombinerInputParameterfvNV");
  glGetFinalCombinerInputParameterivNV = (PFNGLGETFINALCOMBINERINPUTPARAMETERIVNVPROC)SDL_GL_GetProcAddress("glGetFinalCombinerInputParameterivNV");
#endif
#ifdef SAGE_GL_NV_fog_distance
#endif
#ifdef SAGE_GL_NV_texgen_emboss
#endif
#ifdef SAGE_GL_NV_blend_square
#endif
#ifdef SAGE_GL_NV_texture_env_combine4
#endif
#ifdef SAGE_GL_MESA_resize_buffers
  glResizeBuffersMESA = (PFNGLRESIZEBUFFERSMESAPROC)SDL_GL_GetProcAddress("glResizeBuffersMESA");
#endif
#ifdef SAGE_GL_MESA_window_pos
  glWindowPos2dMESA = (PFNGLWINDOWPOS2DMESAPROC)SDL_GL_GetProcAddress("glWindowPos2dMESA");
  glWindowPos2dvMESA = (PFNGLWINDOWPOS2DVMESAPROC)SDL_GL_GetProcAddress("glWindowPos2dvMESA");
  glWindowPos2fMESA = (PFNGLWINDOWPOS2FMESAPROC)SDL_GL_GetProcAddress("glWindowPos2fMESA");
  glWindowPos2fvMESA = (PFNGLWINDOWPOS2FVMESAPROC)SDL_GL_GetProcAddress("glWindowPos2fvMESA");
  glWindowPos2iMESA = (PFNGLWINDOWPOS2IMESAPROC)SDL_GL_GetProcAddress("glWindowPos2iMESA");
  glWindowPos2ivMESA = (PFNGLWINDOWPOS2IVMESAPROC)SDL_GL_GetProcAddress("glWindowPos2ivMESA");
  glWindowPos2sMESA = (PFNGLWINDOWPOS2SMESAPROC)SDL_GL_GetProcAddress("glWindowPos2sMESA");
  glWindowPos2svMESA = (PFNGLWINDOWPOS2SVMESAPROC)SDL_GL_GetProcAddress("glWindowPos2svMESA");
  glWindowPos3dMESA = (PFNGLWINDOWPOS3DMESAPROC)SDL_GL_GetProcAddress("glWindowPos3dMESA");
  glWindowPos3dvMESA = (PFNGLWINDOWPOS3DVMESAPROC)SDL_GL_GetProcAddress("glWindowPos3dvMESA");
  glWindowPos3fMESA = (PFNGLWINDOWPOS3FMESAPROC)SDL_GL_GetProcAddress("glWindowPos3fMESA");
  glWindowPos3fvMESA = (PFNGLWINDOWPOS3FVMESAPROC)SDL_GL_GetProcAddress("glWindowPos3fvMESA");
  glWindowPos3iMESA = (PFNGLWINDOWPOS3IMESAPROC)SDL_GL_GetProcAddress("glWindowPos3iMESA");
  glWindowPos3ivMESA = (PFNGLWINDOWPOS3IVMESAPROC)SDL_GL_GetProcAddress("glWindowPos3ivMESA");
  glWindowPos3sMESA = (PFNGLWINDOWPOS3SMESAPROC)SDL_GL_GetProcAddress("glWindowPos3sMESA");
  glWindowPos3svMESA = (PFNGLWINDOWPOS3SVMESAPROC)SDL_GL_GetProcAddress("glWindowPos3svMESA");
  glWindowPos4dMESA = (PFNGLWINDOWPOS4DMESAPROC)SDL_GL_GetProcAddress("glWindowPos4dMESA");
  glWindowPos4dvMESA = (PFNGLWINDOWPOS4DVMESAPROC)SDL_GL_GetProcAddress("glWindowPos4dvMESA");
  glWindowPos4fMESA = (PFNGLWINDOWPOS4FMESAPROC)SDL_GL_GetProcAddress("glWindowPos4fMESA");
  glWindowPos4fvMESA = (PFNGLWINDOWPOS4FVMESAPROC)SDL_GL_GetProcAddress("glWindowPos4fvMESA");
  glWindowPos4iMESA = (PFNGLWINDOWPOS4IMESAPROC)SDL_GL_GetProcAddress("glWindowPos4iMESA");
  glWindowPos4ivMESA = (PFNGLWINDOWPOS4IVMESAPROC)SDL_GL_GetProcAddress("glWindowPos4ivMESA");
  glWindowPos4sMESA = (PFNGLWINDOWPOS4SMESAPROC)SDL_GL_GetProcAddress("glWindowPos4sMESA");
  glWindowPos4svMESA = (PFNGLWINDOWPOS4SVMESAPROC)SDL_GL_GetProcAddress("glWindowPos4svMESA");
#endif
#ifdef SAGE_GL_IBM_cull_vertex
#endif
#ifdef SAGE_GL_IBM_multimode_draw_arrays
  glMultiModeDrawArraysIBM = (PFNGLMULTIMODEDRAWARRAYSIBMPROC)SDL_GL_GetProcAddress("glMultiModeDrawArraysIBM");
  glMultiModeDrawElementsIBM = (PFNGLMULTIMODEDRAWELEMENTSIBMPROC)SDL_GL_GetProcAddress("glMultiModeDrawElementsIBM");
#endif
#ifdef SAGE_GL_IBM_vertex_array_lists
  glColorPointerListIBM = (PFNGLCOLORPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glColorPointerListIBM");
  glSecondaryColorPointerListIBM = (PFNGLSECONDARYCOLORPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glSecondaryColorPointerListIBM");
  glEdgeFlagPointerListIBM = (PFNGLEDGEFLAGPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glEdgeFlagPointerListIBM");
  glFogCoordPointerListIBM = (PFNGLFOGCOORDPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glFogCoordPointerListIBM");
  glIndexPointerListIBM = (PFNGLINDEXPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glIndexPointerListIBM");
  glNormalPointerListIBM = (PFNGLNORMALPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glNormalPointerListIBM");
  glTexCoordPointerListIBM = (PFNGLTEXCOORDPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glTexCoordPointerListIBM");
  glVertexPointerListIBM = (PFNGLVERTEXPOINTERLISTIBMPROC)SDL_GL_GetProcAddress("glVertexPointerListIBM");
#endif
#ifdef SAGE_GL_SGIX_subsample
#endif
#ifdef SAGE_GL_SGIX_ycrcba
#endif
#ifdef SAGE_GL_SGIX_ycrcb_subsample
#endif
#ifdef SAGE_GL_SGIX_depth_pass_instrument
#endif
#ifdef SAGE_GL_3DFX_texture_compression_FXT1
#endif
#ifdef SAGE_GL_3DFX_multisample
#endif
#ifdef SAGE_GL_3DFX_tbuffer
  glTbufferMask3DFX = (PFNGLTBUFFERMASK3DFXPROC)SDL_GL_GetProcAddress("glTbufferMask3DFX");
#endif
#ifdef SAGE_GL_EXT_multisample
  glSampleMaskEXT = (PFNGLSAMPLEMASKEXTPROC)SDL_GL_GetProcAddress("glSampleMaskEXT");
  glSamplePatternEXT = (PFNGLSAMPLEPATTERNEXTPROC)SDL_GL_GetProcAddress("glSamplePatternEXT");
#endif
#ifdef SAGE_GL_SGI_vertex_preclip
#endif
#ifdef SAGE_GL_SGIX_convolution_accuracy
#endif
#ifdef SAGE_GL_SGIX_resample
#endif
#ifdef SAGE_GL_SGIS_point_line_texgen
#endif
#ifdef SAGE_GL_SGIS_texture_color_mask
  glTextureColorMaskSGIS = (PFNGLTEXTURECOLORMASKSGISPROC)SDL_GL_GetProcAddress("glTextureColorMaskSGIS");
#endif
#ifdef SAGE_GL_SGIX_igloo_interface
  glIglooInterfaceSGIX = (PFNGLIGLOOINTERFACESGIXPROC)SDL_GL_GetProcAddress("glIglooInterfaceSGIX");
#endif
#ifdef SAGE_GL_EXT_texture_env_dot3
#endif
  sage_ext[GL_ARB_MULTITEXTURE] = isExtensionSupported("GL_ARB_multitexture");
  sage_ext[GL_ARB_TRANSPOSE_MATRIX] = isExtensionSupported("GL_ARB_transpose_matrix");
  sage_ext[GL_ARB_MULTISAMPLE] = isExtensionSupported("GL_ARB_multisample");
  sage_ext[GL_ARB_TEXTURE_ENV_ADD] = isExtensionSupported("GL_ARB_texture_env_add");
  sage_ext[GL_ARB_TEXTURE_CUBE_MAP] = isExtensionSupported("GL_ARB_texture_cube_map");
  sage_ext[GL_ARB_TEXTURE_COMPRESSION] = isExtensionSupported("GL_ARB_texture_compression");
  sage_ext[GL_EXT_ABGR] = isExtensionSupported("GL_EXT_abgr");
  sage_ext[GL_EXT_BLEND_COLOR] = isExtensionSupported("GL_EXT_blend_color");
  sage_ext[GL_EXT_POLYGON_OFFSET] = isExtensionSupported("GL_EXT_polygon_offset");
  sage_ext[GL_EXT_TEXTURE] = isExtensionSupported("GL_EXT_texture");
  sage_ext[GL_EXT_TEXTURE3D] = isExtensionSupported("GL_EXT_texture3D");
  sage_ext[GL_SGIS_TEXTURE_FILTER4] = isExtensionSupported("GL_SGIS_texture_filter4");
  sage_ext[GL_EXT_SUBTEXTURE] = isExtensionSupported("GL_EXT_subtexture");
  sage_ext[GL_EXT_COPY_TEXTURE] = isExtensionSupported("GL_EXT_copy_texture");
  sage_ext[GL_EXT_HISTOGRAM] = isExtensionSupported("GL_EXT_histogram");
  sage_ext[GL_EXT_CONVOLUTION] = isExtensionSupported("GL_EXT_convolution");
  sage_ext[GL_EXT_COLOR_MATRIX] = isExtensionSupported("GL_EXT_color_matrix");
  sage_ext[GL_SGI_COLOR_TABLE] = isExtensionSupported("GL_SGI_color_table");
  sage_ext[GL_SGIX_PIXEL_TEXTURE] = isExtensionSupported("GL_SGIX_pixel_texture");
  sage_ext[GL_SGIS_PIXEL_TEXTURE] = isExtensionSupported("GL_SGIS_pixel_texture");
  sage_ext[GL_SGIS_TEXTURE4D] = isExtensionSupported("GL_SGIS_texture4D");
  sage_ext[GL_SGI_TEXTURE_COLOR_TABLE] = isExtensionSupported("GL_SGI_texture_color_table");
  sage_ext[GL_EXT_CMYKA] = isExtensionSupported("GL_EXT_cmyka");
  sage_ext[GL_EXT_TEXTURE_OBJECT] = isExtensionSupported("GL_EXT_texture_object");
  sage_ext[GL_SGIS_DETAIL_TEXTURE] = isExtensionSupported("GL_SGIS_detail_texture");
  sage_ext[GL_SGIS_SHARPEN_TEXTURE] = isExtensionSupported("GL_SGIS_sharpen_texture");
  sage_ext[GL_EXT_PACKED_PIXELS] = isExtensionSupported("GL_EXT_packed_pixels");
  sage_ext[GL_SGIS_TEXTURE_LOD] = isExtensionSupported("GL_SGIS_texture_lod");
  sage_ext[GL_SGIS_MULTISAMPLE] = isExtensionSupported("GL_SGIS_multisample");
  sage_ext[GL_EXT_RESCALE_NORMAL] = isExtensionSupported("GL_EXT_rescale_normal");
  sage_ext[GL_EXT_VERTEX_ARRAY] = isExtensionSupported("GL_EXT_vertex_array");
  sage_ext[GL_EXT_MISC_ATTRIBUTE] = isExtensionSupported("GL_EXT_misc_attribute");
  sage_ext[GL_SGIS_GENERATE_MIPMAP] = isExtensionSupported("GL_SGIS_generate_mipmap");
  sage_ext[GL_SGIX_CLIPMAP] = isExtensionSupported("GL_SGIX_clipmap");
  sage_ext[GL_SGIX_SHADOW] = isExtensionSupported("GL_SGIX_shadow");
  sage_ext[GL_SGIS_TEXTURE_EDGE_CLAMP] = isExtensionSupported("GL_SGIS_texture_edge_clamp");
  sage_ext[GL_SGIS_TEXTURE_BORDER_CLAMP] = isExtensionSupported("GL_SGIS_texture_border_clamp");
  sage_ext[GL_EXT_BLEND_MINMAX] = isExtensionSupported("GL_EXT_blend_minmax");
  sage_ext[GL_EXT_BLEND_SUBTRACT] = isExtensionSupported("GL_EXT_blend_subtract");
  sage_ext[GL_EXT_BLEND_LOGIC_OP] = isExtensionSupported("GL_EXT_blend_logic_op");
  sage_ext[GL_SGIX_INTERLACE] = isExtensionSupported("GL_SGIX_interlace");
  sage_ext[GL_SGIX_PIXEL_TILES] = isExtensionSupported("GL_SGIX_pixel_tiles");
  sage_ext[GL_SGIX_TEXTURE_SELECT] = isExtensionSupported("GL_SGIX_texture_select");
  sage_ext[GL_SGIX_SPRITE] = isExtensionSupported("GL_SGIX_sprite");
  sage_ext[GL_SGIX_TEXTURE_MULTI_BUFFER] = isExtensionSupported("GL_SGIX_texture_multi_buffer");
  sage_ext[GL_EXT_POINT_PARAMETERS] = isExtensionSupported("GL_EXT_point_parameters");
  sage_ext[GL_SGIX_INSTRUMENTS] = isExtensionSupported("GL_SGIX_instruments");
  sage_ext[GL_SGIX_TEXTURE_SCALE_BIAS] = isExtensionSupported("GL_SGIX_texture_scale_bias");
  sage_ext[GL_SGIX_FRAMEZOOM] = isExtensionSupported("GL_SGIX_framezoom");
  sage_ext[GL_SGIX_TAG_SAMPLE_BUFFER] = isExtensionSupported("GL_SGIX_tag_sample_buffer");
  sage_ext[GL_SGIX_POLYNOMIAL_FFD] = isExtensionSupported("GL_SGIX_polynomial_ffd");
  sage_ext[GL_SGIX_REFERENCE_PLANE] = isExtensionSupported("GL_SGIX_reference_plane");
  sage_ext[GL_SGIX_FLUSH_RASTER] = isExtensionSupported("GL_SGIX_flush_raster");
  sage_ext[GL_SGIX_DEPTH_TEXTURE] = isExtensionSupported("GL_SGIX_depth_texture");
  sage_ext[GL_SGIS_FOG_FUNCTION] = isExtensionSupported("GL_SGIS_fog_function");
  sage_ext[GL_SGIX_FOG_OFFSET] = isExtensionSupported("GL_SGIX_fog_offset");
  sage_ext[GL_HP_IMAGE_TRANSFORM] = isExtensionSupported("GL_HP_image_transform");
  sage_ext[GL_HP_CONVOLUTION_BORDER_MODES] = isExtensionSupported("GL_HP_convolution_border_modes");
  sage_ext[GL_SGIX_TEXTURE_ADD_ENV] = isExtensionSupported("GL_SGIX_texture_add_env");
  sage_ext[GL_EXT_COLOR_SUBTABLE] = isExtensionSupported("GL_EXT_color_subtable");
  sage_ext[GL_PGI_VERTEX_HINTS] = isExtensionSupported("GL_PGI_vertex_hints");
  sage_ext[GL_PGI_MISC_HINTS] = isExtensionSupported("GL_PGI_misc_hints");
  sage_ext[GL_EXT_PALETTED_TEXTURE] = isExtensionSupported("GL_EXT_paletted_texture");
  sage_ext[GL_EXT_CLIP_VOLUME_HINT] = isExtensionSupported("GL_EXT_clip_volume_hint");
  sage_ext[GL_SGIX_LIST_PRIORITY] = isExtensionSupported("GL_SGIX_list_priority");
  sage_ext[GL_SGIX_IR_INSTRUMENT1] = isExtensionSupported("GL_SGIX_ir_instrument1");
  sage_ext[GL_SGIX_CALLIGRAPHIC_FRAGMENT] = isExtensionSupported("GL_SGIX_calligraphic_fragment");
  sage_ext[GL_SGIX_TEXTURE_LOD_BIAS] = isExtensionSupported("GL_SGIX_texture_lod_bias");
  sage_ext[GL_SGIX_SHADOW_AMBIENT] = isExtensionSupported("GL_SGIX_shadow_ambient");
  sage_ext[GL_EXT_INDEX_TEXTURE] = isExtensionSupported("GL_EXT_index_texture");
  sage_ext[GL_EXT_INDEX_MATERIAL] = isExtensionSupported("GL_EXT_index_material");
  sage_ext[GL_EXT_INDEX_FUNC] = isExtensionSupported("GL_EXT_index_func");
  sage_ext[GL_EXT_INDEX_ARRAY_FORMATS] = isExtensionSupported("GL_EXT_index_array_formats");
  sage_ext[GL_EXT_COMPILED_VERTEX_ARRAY] = isExtensionSupported("GL_EXT_compiled_vertex_array");
  sage_ext[GL_EXT_CULL_VERTEX] = isExtensionSupported("GL_EXT_cull_vertex");
  sage_ext[GL_SGIX_YCRCB] = isExtensionSupported("GL_SGIX_ycrcb");
  sage_ext[GL_SGIX_FRAGMENT_LIGHTING] = isExtensionSupported("GL_SGIX_fragment_lighting");
  sage_ext[GL_IBM_RASTERPOS_CLIP] = isExtensionSupported("GL_IBM_rasterpos_clip");
  sage_ext[GL_HP_TEXTURE_LIGHTING] = isExtensionSupported("GL_HP_texture_lighting");
  sage_ext[GL_EXT_DRAW_RANGE_ELEMENTS] = isExtensionSupported("GL_EXT_draw_range_elements");
  sage_ext[GL_WIN_PHONG_SHADING] = isExtensionSupported("GL_WIN_phong_shading");
  sage_ext[GL_WIN_SPECULAR_FOG] = isExtensionSupported("GL_WIN_specular_fog");
  sage_ext[GL_EXT_LIGHT_TEXTURE] = isExtensionSupported("GL_EXT_light_texture");
  sage_ext[GL_SGIX_BLEND_ALPHA_MINMAX] = isExtensionSupported("GL_SGIX_blend_alpha_minmax");
  sage_ext[GL_EXT_BGRA] = isExtensionSupported("GL_EXT_bgra");
  sage_ext[GL_SGIX_ASYNC] = isExtensionSupported("GL_SGIX_async");
  sage_ext[GL_SGIX_ASYNC_PIXEL] = isExtensionSupported("GL_SGIX_async_pixel");
  sage_ext[GL_SGIX_ASYNC_HISTOGRAM] = isExtensionSupported("GL_SGIX_async_histogram");
  sage_ext[GL_INTEL_PARALLEL_ARRAYS] = isExtensionSupported("GL_INTEL_parallel_arrays");
  sage_ext[GL_HP_OCCLUSION_TEST] = isExtensionSupported("GL_HP_occlusion_test");
  sage_ext[GL_EXT_PIXEL_TRANSFORM] = isExtensionSupported("GL_EXT_pixel_transform");
  sage_ext[GL_EXT_PIXEL_TRANSFORM_COLOR_TABLE] = isExtensionSupported("GL_EXT_pixel_transform_color_table");
  sage_ext[GL_EXT_SHARED_TEXTURE_PALETTE] = isExtensionSupported("GL_EXT_shared_texture_palette");
  sage_ext[GL_EXT_SEPARATE_SPECULAR_COLOR] = isExtensionSupported("GL_EXT_separate_specular_color");
  sage_ext[GL_EXT_SECONDARY_COLOR] = isExtensionSupported("GL_EXT_secondary_color");
  sage_ext[GL_EXT_TEXTURE_PERTURB_NORMAL] = isExtensionSupported("GL_EXT_texture_perturb_normal");
  sage_ext[GL_EXT_MULTI_DRAW_ARRAYS] = isExtensionSupported("GL_EXT_multi_draw_arrays");
  sage_ext[GL_EXT_FOG_COORD] = isExtensionSupported("GL_EXT_fog_coord");
  sage_ext[GL_REND_SCREEN_COORDINATES] = isExtensionSupported("GL_REND_screen_coordinates");
  sage_ext[GL_EXT_COORDINATE_FRAME] = isExtensionSupported("GL_EXT_coordinate_frame");
  sage_ext[GL_EXT_TEXTURE_ENV_COMBINE] = isExtensionSupported("GL_EXT_texture_env_combine");
  sage_ext[GL_APPLE_SPECULAR_VECTOR] = isExtensionSupported("GL_APPLE_specular_vector");
  sage_ext[GL_APPLE_TRANSFORM_HINT] = isExtensionSupported("GL_APPLE_transform_hint");
  sage_ext[GL_SGIX_FOG_SCALE] = isExtensionSupported("GL_SGIX_fog_scale");
  sage_ext[GL_SUNX_CONSTANT_DATA] = isExtensionSupported("GL_SUNX_constant_data");
  sage_ext[GL_SUN_GLOBAL_ALPHA] = isExtensionSupported("GL_SUN_global_alpha");
  sage_ext[GL_SUN_TRIANGLE_LIST] = isExtensionSupported("GL_SUN_triangle_list");
  sage_ext[GL_SUN_VERTEX] = isExtensionSupported("GL_SUN_vertex");
  sage_ext[GL_EXT_BLEND_FUNC_SEPARATE] = isExtensionSupported("GL_EXT_blend_func_separate");
  sage_ext[GL_INGR_COLOR_CLAMP] = isExtensionSupported("GL_INGR_color_clamp");
  sage_ext[GL_INGR_INTERLACE_READ] = isExtensionSupported("GL_INGR_interlace_read");
  sage_ext[GL_EXT_STENCIL_WRAP] = isExtensionSupported("GL_EXT_stencil_wrap");
  sage_ext[GL_EXT_422_PIXELS] = isExtensionSupported("GL_EXT_422_pixels");
  sage_ext[GL_NV_TEXGEN_REFLECTION] = isExtensionSupported("GL_NV_texgen_reflection");
  sage_ext[GL_SUN_CONVOLUTION_BORDER_MODES] = isExtensionSupported("GL_SUN_convolution_border_modes");
  sage_ext[GL_EXT_TEXTURE_ENV_ADD] = isExtensionSupported("GL_EXT_texture_env_add");
  sage_ext[GL_EXT_TEXTURE_LOD_BIAS] = isExtensionSupported("GL_EXT_texture_lod_bias");
  sage_ext[GL_EXT_TEXTURE_FILTER_ANISOTROPIC] = isExtensionSupported("GL_EXT_texture_filter_anisotropic");
  sage_ext[GL_EXT_VERTEX_WEIGHTING] = isExtensionSupported("GL_EXT_vertex_weighting");
  sage_ext[GL_NV_LIGHT_MAX_EXPONENT] = isExtensionSupported("GL_NV_light_max_exponent");
  sage_ext[GL_NV_VERTEX_ARRAY_RANGE] = isExtensionSupported("GL_NV_vertex_array_range");
  sage_ext[GL_NV_REGISTER_COMBINERS] = isExtensionSupported("GL_NV_register_combiners");
  sage_ext[GL_NV_FOG_DISTANCE] = isExtensionSupported("GL_NV_fog_distance");
  sage_ext[GL_NV_TEXGEN_EMBOSS] = isExtensionSupported("GL_NV_texgen_emboss");
  sage_ext[GL_NV_BLEND_SQUARE] = isExtensionSupported("GL_NV_blend_square");
  sage_ext[GL_NV_TEXTURE_ENV_COMBINE4] = isExtensionSupported("GL_NV_texture_env_combine4");
  sage_ext[GL_MESA_RESIZE_BUFFERS] = isExtensionSupported("GL_MESA_resize_buffers");
  sage_ext[GL_MESA_WINDOW_POS] = isExtensionSupported("GL_MESA_window_pos");
  sage_ext[GL_IBM_CULL_VERTEX] = isExtensionSupported("GL_IBM_cull_vertex");
  sage_ext[GL_IBM_MULTIMODE_DRAW_ARRAYS] = isExtensionSupported("GL_IBM_multimode_draw_arrays");
  sage_ext[GL_IBM_VERTEX_ARRAY_LISTS] = isExtensionSupported("GL_IBM_vertex_array_lists");
  sage_ext[GL_SGIX_SUBSAMPLE] = isExtensionSupported("GL_SGIX_subsample");
  sage_ext[GL_SGIX_YCRCBA] = isExtensionSupported("GL_SGIX_ycrcba");
  sage_ext[GL_SGIX_YCRCB_SUBSAMPLE] = isExtensionSupported("GL_SGIX_ycrcb_subsample");
  sage_ext[GL_SGIX_DEPTH_PASS_INSTRUMENT] = isExtensionSupported("GL_SGIX_depth_pass_instrument");
  sage_ext[GL_3DFX_TEXTURE_COMPRESSION_FXT1] = isExtensionSupported("GL_3DFX_texture_compression_FXT1");
  sage_ext[GL_3DFX_MULTISAMPLE] = isExtensionSupported("GL_3DFX_multisample");
  sage_ext[GL_3DFX_TBUFFER] = isExtensionSupported("GL_3DFX_tbuffer");
  sage_ext[GL_EXT_MULTISAMPLE] = isExtensionSupported("GL_EXT_multisample");
  sage_ext[GL_SGI_VERTEX_PRECLIP] = isExtensionSupported("GL_SGI_vertex_preclip");
  sage_ext[GL_SGIX_CONVOLUTION_ACCURACY] = isExtensionSupported("GL_SGIX_convolution_accuracy");
  sage_ext[GL_SGIX_RESAMPLE] = isExtensionSupported("GL_SGIX_resample");
  sage_ext[GL_SGIS_POINT_LINE_TEXGEN] = isExtensionSupported("GL_SGIS_point_line_texgen");
  sage_ext[GL_SGIS_TEXTURE_COLOR_MASK] = isExtensionSupported("GL_SGIS_texture_color_mask");
  sage_ext[GL_SGIX_IGLOO_INTERFACE] = isExtensionSupported("GL_SGIX_igloo_interface");
  sage_ext[GL_EXT_TEXTURE_ENV_DOT3] = isExtensionSupported("GL_EXT_texture_env_dot3");
}
